"use client";

import type { ReactNode } from "react";
import type { DecisionItem, MatrixRow, RadarItem, WorkforceCounts } from "@/lib/widget-data/wave2";
import { ClientWidgetPage } from "./client-page";
import { Freshness, useWidgetData } from "./data-widgets";
import { StatusCard } from "./widget-shell";

function DataState<T>({result,empty,emptyTitle,children}:{result:ReturnType<typeof useWidgetData<T>>;empty:(data:T)=>boolean;emptyTitle?:string;children:(data:T)=>ReactNode}){
  if(result.state!=="success")return <StatusCard state={result.state} detail={result.detail}/>;
  if(!result.data||empty(result.data))return <StatusCard state="empty" title={emptyTitle}/>;
  return <>{children(result.data)}<Freshness at={result.generatedAt}/></>;
}

export function HealthMatrixWidget(){const result=useWidgetData<{rows:MatrixRow[]}>("/api/widgets/health-matrix");return <ClientWidgetPage code="CW-12 · HEALTH MATRIX" title="Business Health Matrix" footer="Read-only · B09/B10/B08 · Archive=false">{()=> <DataState result={result} empty={data=>!data.rows.length}>{data=><section className="matrix-list">{data.rows.map((row,index)=><article key={`${row.domain}-${index}`}><strong>{row.domain}</strong><span>{row.scoreOrState}</span><b className={row.status.toLowerCase().replace(" ","-")}>{row.status}</b><small>{row.trend}</small></article>)}</section>}</DataState>}</ClientWidgetPage>}

export function WorkforceStatusWidget(){const result=useWidgetData<WorkforceCounts>("/api/widgets/workforce-status");const labels:[keyof WorkforceCounts,string][]=[["healthy","Healthy"],["attention","Attention"],["waiting","Waiting"],["degraded","Degraded"],["offline","Offline"]];return <ClientWidgetPage code="CW-13 · DIGITAL WORKFORCE STATUS" title="Digital Workforce Status" footer="Read-only · B08 · Archive=false · Status≠RETIRED">{()=> <DataState result={result} empty={data=>data.totalActive===0} emptyTitle="No active digital workers are currently populated.">{data=><section className="workforce-grid">{labels.map(([key,label])=><article key={key}><p className="eyebrow">{label}</p><strong className={key}>{data[key]}</strong></article>)}<article><p className="eyebrow">Total Active</p><strong>{data.totalActive}</strong></article></section>}</DataState>}</ClientWidgetPage>}

export function OpportunityRadarWidget(){const result=useWidgetData<{items:RadarItem[]}>("/api/widgets/opportunity-radar");return <ClientWidgetPage code="CW-15 · OPPORTUNITY RADAR" title="Opportunity Radar" footer="Read-only · B03 · Archive=false · Stage≠LOST">{()=> <DataState result={result} empty={data=>!data.items.length} emptyTitle="No live opportunities are currently populated.">{data=><section className="radar-list">{data.items.map((item,index)=><article key={`${item.opportunity}-${index}`}><header><span className="mode-chip">#{index+1} · {item.tier||"UNTIERED"}</span><b>{item.stage||"UNSTAGED"}</b></header><h2>{item.opportunity||"Untitled opportunity"}</h2><p>{item.company}</p><dl><dt>Score</dt><dd>{item.score??"—"}</dd><dt>Estimated Value</dt><dd>{item.estimatedValue===null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(item.estimatedValue)}</dd></dl></article>)}</section>}</DataState>}</ClientWidgetPage>}

export function DecisionQueueWidget(){const result=useWidgetData<{items:DecisionItem[]}>("/api/widgets/decision-queue");return <ClientWidgetPage code="CW-16 · DECISION QUEUE" title="Decision Queue" footer="Read-only · B05 · OPEN/REVIEWING · Archive=false">{()=> <DataState result={result} empty={data=>!data.items.length} emptyTitle="No open decisions are currently populated.">{data=><section className="decision-list">{data.items.map((item,index)=><article key={`${item.decision}-${index}`}><header><span className="mode-chip">{item.impact}</span><b>{item.urgency}</b></header><h2>{item.decision}</h2><p>{item.recommendation||"No recommendation populated"}</p><small>{item.domain} · {item.ageDays===null?"Age unknown":`${item.ageDays} days open`}</small></article>)}</section>}</DataState>}</ClientWidgetPage>}

export function DailyBriefWidget(){const result=useWidgetData<{items:string[]}>("/api/widgets/daily-brief");return <ClientWidgetPage code="CW-18 · DAILY BRIEF" title="Daily Brief" footer="Executive: B03/B05/B07/B08/B10 · Personal shell: fixture only">{config=>config.mode==="personal-shell"?<><section className="fixture-banner">FIXTURE LAYOUT · PERSONAL READS 0</section><section className="brief-list"><article>Spiritual alignment — fixture</article><article>Family priority — fixture</article><article>Personal capacity — fixture</article></section></>:<DataState result={result} empty={data=>!data.items.length}>{data=><section className="brief-list">{data.items.map((item,index)=><article key={item}><span>{String(index+1).padStart(2,"0")}</span><strong>{item}</strong></article>)}</section>}</DataState>}</ClientWidgetPage>}
