"use client";

import { useEffect, useState, type CSSProperties, type ReactNode } from "react";
import { alignmentStatus, attentionValidation, clampProgress, countdownParts, deltaStatus } from "@/lib/widget-data/wave2";
import { ClientWidgetPage } from "./client-page";
import { StatusCard } from "./widget-shell";

function Gate({context,children}:{context?:string;children:ReactNode}){const state=context?.toLowerCase();if(state==="loading"||state==="empty"||state==="error"||state==="disabled")return <StatusCard state={state}/>;return <>{children}</>}

export function CountdownWidget(){const [now,setNow]=useState<number|null>(null);useEffect(()=>{const first=window.setTimeout(()=>setNow(Date.now()),0);const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>{clearTimeout(first);clearInterval(id)}},[]);return <ClientWidgetPage code="CW-03 · COUNTDOWN" title="Milestone Countdown" footer="Local/query configuration · Notion reads 0 · writes 0">{config=>{const fallback=now===null?null:now+7*86_400_000;const target=config.target?Date.parse(config.target):fallback;if(now===null)return <StatusCard state="loading"/>;if(target===null)return <StatusCard state="error" title="Invalid target date" detail="Provide a valid ISO target date. No fallback truth was invented."/>;const parts=countdownParts(target,now);if(!parts)return <StatusCard state="error" title="Invalid target date" detail="Provide a valid ISO target date. No fallback truth was invented."/>;return <Gate context={config.context}><section className="countdown"><p className="eyebrow">{config.label||"LOCAL MILESTONE"}</p><div className="countdown-grid"><span><strong>{parts.days}</strong><small>Days</small></span><span><strong>{parts.hours}</strong><small>Hours</small></span><span><strong>{parts.minutes}</strong><small>Minutes</small></span></div><p className={`completion ${parts.complete?"healthy":"attention"}`}>{parts.complete?"COMPLETE":"IN PROGRESS"}</p><time dateTime={new Date(target).toISOString()}>{new Date(target).toLocaleString("en-US",{timeZone:"America/Chicago",dateStyle:"medium",timeStyle:"short"})} CT</time></section></Gate>}}</ClientWidgetPage>}

const alignmentAreas=[{label:"Spiritual",offset:4},{label:"Family",offset:-3},{label:"Brand",offset:2},{label:"Growth",offset:-6}];
export function AlignmentWidget(){return <ClientWidgetPage code="CW-05 · ALIGNMENT GAUGE" title="Personal Alignment" footer="FIXTURE DATA · Personal reads 0 · production Personal embed deferred">{config=>{const value=clampProgress(config.value??78);return <Gate context={config.context}><section className="fixture-banner">FIXTURE DATA · PRESENTATION LOGIC ONLY</section><section className="gauge-layout"><ProgressVisual value={value}/><div><p className="eyebrow">OVERALL ALIGNMENT</p><strong className={`gauge-status ${alignmentStatus(value).toLowerCase().replace(" ","-")}`}>{alignmentStatus(value)}</strong><div className="area-bars">{alignmentAreas.map(area=>{const score=clampProgress(value+area.offset);return <div key={area.label}><span>{area.label}</span><progress max="100" value={score} aria-label={`${area.label} ${score}%`}/><b>{score}</b></div>})}</div></div></section></Gate>}}</ClientWidgetPage>}

export function ProgressWidget(){return <ClientWidgetPage code="CW-06 · PROGRESS RING" title="Progress" footer="Local configuration · no canonical reads or writes">{config=>{const value=clampProgress(config.value??50);return <Gate context={config.context}><section className="progress-layout"><ProgressVisual value={value}/><div><p className="eyebrow">{config.label||"LOCAL PROGRESS"}</p><h2>{config.mode||alignmentStatus(value)}</h2><p className="muted">{config.target?`Target ${config.target}`:"No target configured"}</p></div></section></Gate>}}</ClientWidgetPage>}

function ProgressVisual({value}:{value:number}){return <div className="progress-ring" style={{"--progress":`${value*3.6}deg`} as CSSProperties} role="img" aria-label={`${value}% complete`}><span>{Math.round(value)}%</span></div>}

const allocation=[{name:"Strategy",target:20,actual:18},{name:"Product",target:20,actual:24},{name:"Engineering",target:15,actual:20},{name:"Revenue",target:15,actual:12},{name:"Brand",target:10,actual:8},{name:"Relationships",target:10,actual:9},{name:"Personal",target:10,actual:9}];
export function AttentionWidget(){return <ClientWidgetPage code="CW-09 · ATTENTION ALLOCATION" title="Attention Allocation" footer="FIXTURE DATA · P12 reads 0 · persistence 0">{config=>{const total=Math.max(0,config.targetTotal??100),factor=total/100;return <Gate context={config.context}><section className="fixture-banner">FIXTURE DATA · TARGET VS ACTUAL</section><p className={`allocation-check ${total===100?"healthy":"attention"}`}>{attentionValidation(total)}</p><section className="allocation-list">{allocation.map(item=>{const target=Math.round(item.target*factor*10)/10,variance=Math.round((item.actual-target)*10)/10;return <article key={item.name}><header><strong>{item.name}</strong><span>{variance>0?"+":""}{variance}%</span></header><div><i style={{width:`${Math.min(100,target)}%`}}/><b style={{width:`${Math.min(100,item.actual)}%`}}/></div><small>Target {target}% · Actual {item.actual}%</small></article>})}</section></Gate>}}</ClientWidgetPage>}

const weekly=[{name:"Spiritual",current:84,prior:80},{name:"Family",current:78,prior:82},{name:"Brand",current:73,prior:70},{name:"Growth",current:81,prior:null},{name:"Capacity",current:null,prior:76}];
export function WeeklyReviewWidget(){return <ClientWidgetPage code="CW-19 · WEEKLY REVIEW PULSE" title="Weekly Review Pulse" footer="FIXTURE DATA · Personal reads 0 · production Personal embed deferred">{config=><Gate context={config.context}><section className="fixture-banner">FIXTURE DATA · PRESENTATION LOGIC ONLY</section><section className="review-list">{weekly.map(item=>{const state=deltaStatus(item.current,item.prior);return <article key={item.name}><strong>{item.name}</strong><span>{item.current??"UNKNOWN"}</span><small>Prior {item.prior??"—"}</small><b className={state.status==="UP"?"healthy":state.status==="DOWN"?"critical":"attention"}>{state.delta===null?state.status:`${state.delta>0?"+":""}${state.delta} · ${state.status}`}</b></article>})}</section></Gate>}</ClientWidgetPage>}
