import { expect, test, type Page } from "@playwright/test";

const personal={identity:{name:"David Craig",context:"Personal Intelligence System"},attention:[],focus:null,decisions:[],signals:[],media:null,rhythms:{active:0,attention:0,healthy:0},navigation:[]};
const business={identity:{name:"ProdigyIQ Technologies",context:"Executive Command"},requiresDavid:[],pulse:[],worktelli:{generation:"Not populated",certification:"Not populated",productState:"Not populated",primaryConstraint:"No active constraint",currentPacket:"No current packet",latestQualification:"Not populated"},revenue:{activeCount:0,estimatedValue:0,topOpportunity:null},workforce:{healthy:0,attention:0,waiting:0,degraded:0,offline:0,totalActive:0},decisions:[],exceptions:[],signals:[],navigation:[]};
const ok=(data:unknown)=>JSON.stringify({ok:true,data,source:"notion",generatedAt:"2026-09-15T12:00:00.000Z",error:null});
async function shell(page:Page,scope:"personal"|"business",onRead?:()=>void){await page.route(`**/api/os/${scope}/command`,route=>{onRead?.();return route.fulfill({contentType:"application/json",body:ok(scope==="personal"?personal:business)})})}
async function actionApi(page:Page,result:{ok:boolean;errorCode?:string}={ok:true}){await page.route("**/api/actions/session",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,csrfToken:"test-csrf",expiresAt:"2026-09-16T12:00:00.000Z"})}));await page.route("**/api/actions/*/*",route=>route.fulfill({status:result.ok?200:503,contentType:"application/json",body:JSON.stringify(result.ok?{ok:true,actionId:"A-P01",recordId:"record",recordUrl:"https://www.notion.so/record",createdAt:"2026-09-15T12:00:00.000Z"}:{ok:false,actionId:"A-P01",errorCode:result.errorCode??"WRITE_FAILED"})}))}

const locations:[string,string,string][]=[
  ["personal","command","A-P01"],["personal","command","A-P02"],["personal","command","A-P03"],["personal","growth","A-P04"],["personal","brand","A-P05"],
  ["business","revenue","A-B01"],["business","executive","A-B02"],["business","executive","A-B03"],["business","executive","A-B04"],["business","workforce","A-B05"],["business","worktelli","A-B06"],
];
for(const [scope,mode,id] of locations)test(`${id} is available in its authorized ${mode} context`,async({page})=>{await shell(page,scope as "personal"|"business");await page.goto(`/os/${scope}/command?mode=${mode}`);const control=page.locator(`[data-action-id="${id}"]`).first();await expect(control).toBeVisible();await control.click();await expect(page.locator(`.action-sheet[data-action-id="${id}"]`)).toBeVisible();await expect(page.locator(".action-sheet")).toContainText("QUICK CAPTURE")});

for(const width of [320,390,430,768,1024,1440])test(`action sheet is usable and overflow-safe at ${width}px`,async({page})=>{await shell(page,"personal");await page.setViewportSize({width,height:900});await page.goto("/os/personal/command");await page.locator('[data-action-id="A-P01"]').first().click();await expect(page.locator(".action-sheet")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();const box=await page.locator(".action-submit").boundingBox();expect(box).not.toBeNull();expect(box!.height).toBeGreaterThanOrEqual(44);expect(box!.x+box!.width).toBeLessThanOrEqual(width)});

test("confirmed capture disables rapid repeats, returns a record link, and refreshes the affected shell",async({page})=>{let writes=0,reads=0;await shell(page,"personal",()=>reads++);await page.route("**/api/actions/session",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,csrfToken:"test-csrf",expiresAt:"2026-09-16T12:00:00.000Z"})}));await page.route("**/api/actions/*/*",async route=>{writes++;await new Promise(resolve=>setTimeout(resolve,500));return route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,actionId:"A-P01",recordId:"record",recordUrl:"https://www.notion.so/record",createdAt:"2026-09-15T12:00:00.000Z"})})});await page.goto("/os/personal/command");await page.locator('[data-action-id="A-P01"]').first().click();await page.locator(".action-sheet label").filter({hasText:"Commitment"}).locator("textarea").fill("<img src=x onerror=alert(1)> Protect the priority");const submit=page.locator(".action-submit");await submit.dblclick();await expect(submit).toBeDisabled();await expect(page.getByText("Commitment captured.",{exact:true})).toBeVisible();await expect(page.getByRole("link",{name:"Manage record ↗"})).toHaveAttribute("href","https://www.notion.so/record");expect(writes).toBe(1);await expect.poll(()=>reads).toBeGreaterThanOrEqual(2);await expect(page.locator("img[src=x]")).toHaveCount(0)});

test("failed capture stays in context, reports nothing saved, and can retry",async({page})=>{await shell(page,"business");await actionApi(page,{ok:false,errorCode:"WRITE_FAILED"});await page.goto("/os/business/command?mode=revenue");await page.locator('[data-action-id="A-B01"]').first().click();await page.locator(".action-sheet textarea").fill("Evaluate governed pilot");await page.getByRole("button",{name:"Capture",exact:true}).click();await expect(page.locator(".action-error")).toContainText("Nothing was saved");await expect(page.locator('.action-sheet[data-action-id="A-B01"]')).toBeVisible();await expect(page.getByRole("button",{name:"Retry",exact:true})).toBeEnabled()});

test("sensitive spiritual captures remain native links and focus sessions stay local",async({page})=>{await shell(page,"personal");await page.goto("/os/personal/command?mode=spiritual");await expect(page.locator('[data-action-id^="A-"]')).toHaveCount(0);for(const link of await page.getByRole("link",{name:"+ Prayer",exact:true}).all())await expect(link).toHaveAttribute("href",/^https:\/\/www\.notion\.so\//);await expect(page.getByTitle("Prayer session timer")).toBeVisible()});

test("Media Theater maps only approved insight and brand-idea captures with source context",async({page})=>{await page.route("**/api/widgets/media**",route=>route.fulfill({contentType:"application/json",body:ok({items:[{id:"media",title:"Reference",mediaType:"VIDEO",platform:"Web",url:"https://example.com/reference",mode:"WRITING",purpose:"Draft",duration:null,relatedContext:"Brand",provider:"external",embedUrl:null}]})}));await page.goto("/os/media?mode=brand");await expect(page.locator('.theater-capture [data-action-id="A-P05"]')).toHaveCount(1);await page.locator('.theater-capture [data-action-id="A-P04"]').click();await expect(page.locator('.action-sheet input[type="url"]')).toHaveValue("https://example.com/reference");await page.getByRole("button",{name:"Close capture"}).click();await page.getByRole("link",{name:"+ Hook"}).click({trial:true})});
