import { expect, test, type Page } from "@playwright/test";

const personal={identity:{name:"David Craig",context:"Personal Intelligence System"},attention:[],focus:null,decisions:[],signals:[],media:null,rhythms:{active:0,attention:0,healthy:0},navigation:[]};
const business={identity:{name:"ProdigyIQ Technologies",context:"Executive Command"},requiresDavid:[],pulse:[],worktelli:{generation:"G2",certification:"CERTIFIED",productState:"PRODUCTION",primaryConstraint:"None",currentPacket:"Qualification",latestQualification:"PASS"},revenue:{activeCount:0,estimatedValue:0,topOpportunity:null},workforce:{healthy:0,attention:0,waiting:0,degraded:0,offline:0,totalActive:0},decisions:[],exceptions:[],signals:[],navigation:[]};
async function mock(page:Page){await page.route("**/api/os/personal/command",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,data:personal,generatedAt:"2026-09-16T00:00:00.000Z"})}));await page.route("**/api/os/business/command",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,data:business,generatedAt:"2026-09-16T00:00:00.000Z"})}));}

test("direct app selector keeps Personal and ProdigyIQ distinct",async({page})=>{await page.goto("/");await expect(page.getByRole("link",{name:"Open Personal OS"})).toHaveAttribute("href","/os/personal?mode=command");await expect(page.getByRole("link",{name:"Open ProdigyIQ OS"})).toHaveAttribute("href","/os/business?mode=executive")});
for(const width of [1024,1440])test(`desktop OS switch is visible and functional at ${width}px`,async({page})=>{await mock(page);await page.setViewportSize({width,height:1000});await page.goto("/os/personal?mode=focus");const personalSwitch=page.getByRole("navigation",{name:"Operating system"});await expect(personalSwitch).toBeVisible();const personalBox=await personalSwitch.boundingBox();expect(personalBox?.width).toBeGreaterThan(0);expect(personalBox?.height).toBeGreaterThan(0);await expect(personalSwitch.getByRole("link",{name:"Personal"})).toHaveAttribute("aria-current","page");await personalSwitch.getByRole("link",{name:"ProdigyIQ"}).click();await expect(page).toHaveURL(/\/os\/business\?mode=executive/);await expect(page.locator("main")).toHaveAttribute("data-mode","executive");const businessSwitch=page.getByRole("navigation",{name:"Operating system"});await expect(businessSwitch.getByRole("link",{name:"ProdigyIQ"})).toHaveAttribute("aria-current","page");await businessSwitch.getByRole("link",{name:"Personal"}).click();await expect(page).toHaveURL(/\/os\/personal\?mode=command/);await expect(page.locator("main")).toHaveAttribute("data-mode","command")});
for(const width of [320,390,430,768])test(`all direct operating modes work at ${width}px`,async({page})=>{await mock(page);await page.setViewportSize({width,height:844});for(const mode of ["command","focus","spiritual","brand","growth","reset"]){await page.goto(`/os/personal?mode=${mode}`);await expect(page.locator("main")).toHaveAttribute("data-mode",mode);await expect(page.getByRole("navigation",{name:"Operating system"})).toBeVisible()}for(const mode of ["executive","revenue","worktelli","engineering","clients","workforce"]){await page.goto(`/os/business?mode=${mode}`);await expect(page.locator("main")).toHaveAttribute("data-mode",mode);expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy()}});
test("manifest declares standalone direct-app metadata",async({request})=>{const response=await request.get("/manifest.webmanifest");expect(response.ok()).toBeTruthy();const manifest=await response.json();expect(manifest).toMatchObject({name:"Craig OS",short_name:"Craig OS",start_url:"/",display:"standalone",background_color:"#12161c",theme_color:"#12161c"});expect(manifest.icons.length).toBeGreaterThanOrEqual(2)});
