import { expect, test, type Page } from "@playwright/test";

const widths=[320,390,430,768,1024,1440];
const modes={focus:"Focus Theater",spiritual:"Spiritual Theater",growth:"Learning Theater",brand:"Creative Theater"} as const;
const personal={identity:{name:"David Craig",context:"Personal Intelligence System"},attention:[],focus:{title:"One priority",detail:"Complete the protected work",progress:50,href:"https://www.notion.so/o"},decisions:[],signals:[],media:null,rhythms:{active:1,attention:0,healthy:1},navigation:[]};
const item=(changes:Record<string,unknown>={})=>({id:"youtube",title:"Deep Work Session",mediaType:"VIDEO",platform:"YouTube",url:"https://youtu.be/abc123XYZ",mode:"DEEP WORK",purpose:"Support the current objective",duration:50,relatedContext:"One priority",provider:"youtube",embedUrl:"https://www.youtube-nocookie.com/embed/abc123XYZ",...changes});
const ok=(items:unknown[])=>JSON.stringify({ok:true,data:{items},source:"notion",generatedAt:"2026-09-15T12:00:00.000Z",error:null});
async function media(page:Page,items:unknown[]){await page.route("**/api/widgets/media**",route=>route.fulfill({contentType:"application/json",body:ok(items)}))}
async function shell(page:Page){await page.route("**/api/os/personal/command",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,data:personal,source:"notion",generatedAt:"2026-09-15T12:00:00.000Z",error:null})}))}

for(const [mode,heading] of Object.entries(modes))for(const width of widths)test(`Media Theater ${mode} is responsive at ${width}px`,async({page})=>{await media(page,[]);const logs:string[]=[];page.on("console",message=>{if(["error","warning"].includes(message.type()))logs.push(message.text())});await page.setViewportSize({width,height:1000});await page.goto(`/os/media?mode=${mode}`);await expect(page.getByRole("heading",{name:heading})).toBeVisible();await expect(page.locator(".theater-status[data-state=empty]")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();expect(logs).toEqual([])});

test("provider embeds are allowlisted and autoplay remains off",async({page})=>{for(const providerItem of [
  item(),
  item({id:"vimeo",title:"Course",platform:"Vimeo",provider:"vimeo",embedUrl:"https://player.vimeo.com/video/1234567",url:"https://vimeo.com/1234567",mediaType:"COURSE"}),
  item({id:"loom",title:"Walkthrough",platform:"Loom",provider:"loom",embedUrl:"https://www.loom.com/embed/abc123",url:"https://www.loom.com/share/abc123",mediaType:"REFERENCE"}),
  item({id:"spotify",title:"Worship",platform:"Spotify",provider:"spotify",embedUrl:"https://open.spotify.com/embed/playlist/123ABC",url:"https://open.spotify.com/playlist/123ABC",mediaType:"MUSIC"}),
]){await media(page,[providerItem]);await page.goto("/os/media?mode=focus");await expect(page.locator(".theater-iframe")).toHaveCount(1);expect(await page.locator("[autoplay]").count()).toBe(0);await page.unroute("**/api/widgets/media**")}});

test("podcast audio and direct video expose truthful native playback states",async({page})=>{await page.route("https://media.example.com/**",route=>route.fulfill({contentType:"audio/wav",body:Buffer.from("UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=","base64")}));await media(page,[item({id:"podcast",title:"Public Podcast",mediaType:"PODCAST",platform:"Direct",provider:"direct-audio",embedUrl:null,url:"https://media.example.com/episode.mp3"}),item({id:"video",title:"Direct Lesson",mediaType:"COURSE",platform:"Direct",provider:"direct-video",embedUrl:null,url:"https://media.example.com/lesson.mp4"})]);await page.goto("/os/media?mode=growth");const audio=page.locator("audio");await expect(audio).toHaveCount(1);await audio.dispatchEvent("canplay");await expect(page.getByText("READY",{exact:true})).toBeVisible();await audio.dispatchEvent("play");await expect(page.getByText("PLAYING",{exact:true})).toBeVisible();await audio.dispatchEvent("pause");await expect(page.getByText("PAUSED",{exact:true})).toBeVisible();await audio.dispatchEvent("ended");await expect(page.getByText("ENDED",{exact:true})).toBeVisible();await page.locator(".theater-queue button").filter({hasText:"Direct Lesson"}).click();await expect(page.locator("audio")).toHaveCount(0);await expect(page.locator("video")).toHaveCount(1);expect(await page.locator("audio,video,iframe").count()).toBe(1)});

test("queue selection retires the prior player and updates current and next",async({page})=>{await media(page,[item(),item({id:"reference",title:"Editorial Reference",mediaType:"REFERENCE",platform:"Web",provider:"external",embedUrl:null,url:"https://example.com/reference"})]);await page.goto("/os/media?mode=brand");await expect(page.getByRole("heading",{name:"Deep Work Session"})).toBeVisible();await page.getByRole("button",{name:/Editorial Reference/}).first().click();await expect(page.getByRole("heading",{name:"Editorial Reference"})).toBeVisible();await expect(page.locator("iframe,audio,video")).toHaveCount(0);await expect(page.getByText("EXTERNAL PROVIDER",{exact:true})).toBeVisible();await expect(page.getByRole("link",{name:"Open in provider ↗"})).toHaveAttribute("href","https://example.com/reference")});

test("mode switching replaces the active context and player",async({page})=>{await page.route("**/api/widgets/media**",route=>{const spiritual=new URL(route.request().url()).searchParams.get("mode")==="spiritual";return route.fulfill({contentType:"application/json",body:ok([spiritual?item({id:"sermon",title:"Current Teaching",mediaType:"SERMON",mode:"SPIRITUAL"}):item({id:"focus-audio",title:"Focus Audio",provider:"direct-audio",embedUrl:null,url:"https://media.example.com/focus.mp3",mediaType:"AUDIO"})])})});await page.goto("/os/media?mode=focus");await expect(page.locator("audio")).toHaveCount(1);await page.getByRole("link",{name:"SPIRITUAL",exact:true}).click();await expect(page.locator('.media-theater[data-theater-mode="spiritual"]')).toBeVisible();await expect(page.getByRole("heading",{name:"Current Teaching"})).toBeVisible();await expect(page.locator("audio")).toHaveCount(0);await expect(page.locator("iframe,audio,video")).toHaveCount(1)});

test("unsupported, invalid, missing, loading, empty, and error states are explicit",async({page})=>{await media(page,[item({id:"external",title:"Podcast Page",mediaType:"PODCAST",provider:"external",embedUrl:null,url:"https://example.com/podcast"})]);await page.goto("/os/media?mode=focus");await expect(page.getByText("This provider does not allow inline playback.")).toBeVisible();await page.unroute("**/api/widgets/media**");await media(page,[item({id:"invalid",title:"Invalid",provider:"unavailable",embedUrl:null,url:null})]);await page.reload();await expect(page.getByText("UNAVAILABLE",{exact:true})).toBeVisible();await expect(page.locator("iframe,audio,video")).toHaveCount(0);await page.unroute("**/api/widgets/media**");await page.route("**/api/widgets/media**",route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({ok:false,data:null,source:"notion",generatedAt:new Date().toISOString(),error:{code:"UPSTREAM_UNAVAILABLE",message:"P11 unavailable"}})}));await page.reload();await expect(page.locator(".theater-status[data-state=error]")).toBeVisible()});

for(const mode of Object.keys(modes))test(`${mode} mode embeds the Theater with bounded captures`,async({page})=>{await shell(page);await media(page,[]);await page.goto(`/os/personal/command?mode=${mode}`);await expect(page.locator(`.media-theater[data-theater-mode="${mode}"]`)).toBeVisible();await expect(page.locator(".theater-capture a").first()).toHaveAttribute("href",/^https:\/\/www\.notion\.so\//);expect(await page.locator(".theater-capture form").count()).toBe(0)});
