import { expect, test, type Page } from "@playwright/test";

const personal={identity:{name:"David Craig",context:"Personal Intelligence System"},attention:[{kind:"COMMITMENT",title:"Protect the priority",detail:"Due today",tone:"attention",href:"https://www.notion.so/a"}],focus:{title:"Ship the verified slice",detail:"Complete the current outcome",progress:42,href:"https://www.notion.so/b"},decisions:[{title:"Choose the next move",meta:"HIGH · OPEN",href:"https://www.notion.so/c"}],signals:[{title:"Capacity is improving",meta:"STRONG · POSITIVE",href:"https://www.notion.so/d"}],media:null,rhythms:{active:4,attention:1,healthy:3},navigation:[]};
const business={identity:{name:"ProdigyIQ Technologies",context:"Executive Command"},requiresDavid:[{kind:"EXCEPTION",title:"Production constraint",detail:"HIGH · TRIAGE",tone:"critical",href:"https://www.notion.so/a"}],pulse:[],worktelli:{generation:"G2",certification:"CERTIFIED",productState:"PRODUCTION",primaryConstraint:"No active constraint",currentPacket:"Qualification",latestQualification:"PASS"},revenue:{activeCount:1,estimatedValue:125000,topOpportunity:{title:"Priority account",detail:"PROPOSAL · $125,000",href:"https://www.notion.so/b"}},workforce:{healthy:2,attention:0,waiting:0,degraded:0,offline:0,totalActive:2},decisions:[{title:"Approve proposal",meta:"HIGH · IMMEDIATE",href:"https://www.notion.so/a"}],exceptions:[{kind:"EXCEPTION",title:"Production constraint",detail:"HIGH · TRIAGE",tone:"critical",href:"https://www.notion.so/a"}],signals:[],navigation:[]};
async function mock(page:Page,scope:"personal"|"business",data:unknown){await page.route(`**/api/os/${scope}/command`,route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,data,generatedAt:"2026-09-16T00:00:00.000Z"})}))}

for(const width of [320,390,430])test(`mobile Personal and Business shells are overflow-safe at ${width}px`,async({page})=>{for(const [scope,data,mode] of [["personal",personal,"command"],["business",business,"executive"]] as const){await mock(page,scope,data);await page.setViewportSize({width,height:844});await page.goto(`/os/${scope}/command?mode=${mode}`);await expect(page.locator("main.os-shell")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();const rail=page.locator(".os-mode-rail");await expect(rail).toBeVisible();const box=await rail.boundingBox();expect(box?.height).toBeGreaterThanOrEqual(44)}});
test("mobile detail uses a bottom sheet and retains current context",async({page})=>{await mock(page,"personal",personal);await page.setViewportSize({width:390,height:844});await page.goto("/os/personal/command?mode=command");await page.getByRole("button",{name:"Inspect Protect the priority"}).click();const sheet=page.getByRole("dialog",{name:"COMMITMENT detail"});await expect(sheet).toBeVisible();const box=await sheet.boundingBox();expect(box?.width).toBeGreaterThan(360);expect(box?.y).toBeGreaterThan(0);await sheet.getByRole("button",{name:"Back to Command"}).click();await expect(page.locator("main")).toHaveAttribute("data-mode","command")});
test("mobile history remains within the Business shell",async({page})=>{await mock(page,"business",business);await page.setViewportSize({width:390,height:844});await page.goto("/os/business/command?mode=executive");await page.getByRole("link",{name:"REVENUE",exact:true}).click();await expect(page.locator("main")).toHaveAttribute("data-mode","revenue");await page.getByRole("link",{name:"WORKTELLI",exact:true}).click();await expect(page.locator("main")).toHaveAttribute("data-mode","worktelli");await page.goBack();await expect(page.locator("main")).toHaveAttribute("data-mode","revenue")});
