import { expect, test, type Page } from "@playwright/test";

const personal={identity:{name:"David Craig",context:"Personal Intelligence System"},attention:[{kind:"COMMITMENT",title:"Protect the priority",detail:"Due today",tone:"attention",href:"https://www.notion.so/c"}],focus:{title:"Worktelli Strategy",detail:"One current objective",progress:40,href:"https://www.notion.so/o"},decisions:[],signals:[],media:null,rhythms:{active:2,attention:0,healthy:1},navigation:[]};
const business={identity:{name:"ProdigyIQ Technologies",context:"Executive Command"},requiresDavid:[],pulse:[{label:"Active opportunities",value:"1",tone:"healthy"},{label:"Open decisions",value:"0",tone:"neutral"},{label:"High / critical exceptions",value:"0",tone:"healthy"},{label:"Active digital workers",value:"2",tone:"healthy"},{label:"Metrics at risk",value:"0",tone:"healthy"},{label:"Production capabilities",value:"1",tone:"healthy"}],worktelli:{generation:"G2",certification:"CERTIFIED",productState:"PRODUCTION",primaryConstraint:"No active constraint",currentPacket:"ENG-22",latestQualification:"PASS"},revenue:{activeCount:1,estimatedValue:125000,topOpportunity:{title:"Priority account",detail:"PROPOSAL · $125,000",href:"https://www.notion.so/o"}},workforce:{healthy:2,attention:0,waiting:0,degraded:0,offline:0,totalActive:2},decisions:[],exceptions:[],signals:[{title:"Customer pull",meta:"HIGH · CLIENT",href:"https://www.notion.so/s"}],navigation:[]};
const personalModes={command:"David Command",focus:"Focus",spiritual:"Spiritual Center",brand:"Brand Studio",growth:"Growth Lab",reset:"Weekly Reset"} as const;
const businessModes={executive:"Executive Command",revenue:"Revenue Command",worktelli:"Worktelli Control",engineering:"Engineering Control",clients:"Client Command",workforce:"Workforce Control"} as const;
const widths=[320,390,430,768,1024,1440];

async function mock(page:Page,scope:"personal"|"business",data:unknown){await page.route(`**/api/os/${scope}/command`,route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,data,source:"notion",generatedAt:"2026-09-15T12:00:00.000Z",error:null})}))}

for(const [mode,heading] of Object.entries(personalModes))test(`Personal ${mode} is directly addressable`,async({page})=>{await mock(page,"personal",personal);await page.goto(`/os/personal/command?mode=${mode}`);await expect(page.locator("main.os-shell")).toHaveAttribute("data-mode",mode);await expect(page.getByRole("heading",{level:1,name:heading})).toBeVisible();await expect(page.locator(`.os-mode-rail a[aria-current="page"]`)).toHaveText(mode.toUpperCase())});
for(const [mode,heading] of Object.entries(businessModes))test(`Business ${mode} is directly addressable`,async({page})=>{await mock(page,"business",business);await page.goto(`/os/business/command?mode=${mode}`);await expect(page.locator("main.os-shell")).toHaveAttribute("data-mode",mode);await expect(page.getByRole("heading",{level:1,name:heading})).toBeVisible();await expect(page.locator(`.os-mode-rail a[aria-current="page"]`)).toHaveText(mode.toUpperCase())});

for(const [scope,modes,data] of [["personal",personalModes,personal],["business",businessModes,business]] as const)for(const [mode] of Object.entries(modes))for(const width of widths)test(`${scope} ${mode} is responsive at ${width}px`,async({page})=>{await mock(page,scope,data);const errors:string[]=[];page.on("console",message=>{if(["error","warning"].includes(message.type()))errors.push(message.text())});await page.setViewportSize({width,height:1000});await page.goto(`/os/${scope}/command?mode=${mode}`);await expect(page.locator(".os-mode-content")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();const selected=page.locator('.os-mode-rail a[aria-current="page"]');const box=await selected.boundingBox();expect(box).not.toBeNull();expect(box!.height).toBeGreaterThanOrEqual(44);expect(errors).toEqual([])});

test("Personal mode switching is client-side, refreshable, and back navigable",async({page})=>{await mock(page,"personal",personal);await page.goto("/os/personal/command?mode=command");await page.getByRole("link",{name:"FOCUS",exact:true}).click();await expect(page).toHaveURL(/mode=focus/);await expect(page.locator("main")).toHaveAttribute("data-mode","focus");await page.getByRole("link",{name:"SPIRITUAL",exact:true}).click();await expect(page.locator("main")).toHaveAttribute("data-mode","spiritual");await page.reload();await expect(page.locator("main")).toHaveAttribute("data-mode","spiritual");await page.goBack();await expect(page.locator("main")).toHaveAttribute("data-mode","focus")});
test("Business mode switching is client-side, refreshable, and back navigable",async({page})=>{await mock(page,"business",business);await page.goto("/os/business/command?mode=executive");await page.getByRole("link",{name:"REVENUE",exact:true}).click();await expect(page.locator("main")).toHaveAttribute("data-mode","revenue");await page.getByRole("link",{name:"WORKTELLI",exact:true}).click();await expect(page.locator("main")).toHaveAttribute("data-mode","worktelli");await page.reload();await expect(page.locator("main")).toHaveAttribute("data-mode","worktelli");await page.goBack();await expect(page.locator("main")).toHaveAttribute("data-mode","revenue")});

test("Focus materially reduces the shell to one objective and local controls",async({page})=>{await mock(page,"personal",personal);await page.goto("/os/personal/command?mode=focus");await expect(page.getByText("One objective. Everything else gets quieter.",{exact:true}).first()).toBeVisible();await expect(page.getByText("CURRENT OBJECTIVE",{exact:true})).toBeVisible();await expect(page.getByTitle("Focus timer")).toBeVisible();await expect(page.locator('.media-theater[data-theater-mode="focus"]')).toBeVisible();await expect(page.getByText("EXECUTIVE PULSE",{exact:true})).toHaveCount(0)});
test("Spiritual is reflective and discloses the sensitive-data boundary",async({page})=>{await mock(page,"personal",personal);await page.goto("/os/personal/command?mode=spiritual");await expect(page.getByText("Be still. Listen well.",{exact:true}).first()).toBeVisible();await expect(page.getByText(/Prayer records remain private/)).toBeVisible();await expect(page.getByTitle("Prayer session timer")).toBeVisible();await expect(page.locator('.media-theater[data-theater-mode="spiritual"]')).toBeVisible()});
test("Executive to Revenue to Worktelli changes the operated context",async({page})=>{await mock(page,"business",business);await page.goto("/os/business/command?mode=executive");await expect(page.getByText("EXECUTIVE PULSE",{exact:true})).toBeVisible();await page.getByRole("link",{name:"REVENUE",exact:true}).click();await expect(page.getByText("OPPORTUNITY RADAR",{exact:true})).toBeVisible();await page.getByRole("link",{name:"WORKTELLI",exact:true}).click();await expect(page.getByText("CURRENT PACKET",{exact:true})).toBeVisible()});
test("Personal and Business registries do not cross",async({page})=>{await mock(page,"personal",personal);await page.goto("/os/personal/command?mode=revenue");await expect(page.locator("main")).toHaveAttribute("data-mode","command");await expect(page.getByRole("link",{name:"EXECUTIVE",exact:true})).toHaveCount(0);await mock(page,"business",business);await page.goto("/os/business/command?mode=spiritual");await expect(page.locator("main")).toHaveAttribute("data-mode","executive");await expect(page.getByRole("link",{name:"SPIRITUAL",exact:true})).toHaveCount(0)});
for(const scope of ["personal","business"] as const)test(`${scope} mode error remains honest`,async({page})=>{await page.route(`**/api/os/${scope}/command`,route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({ok:false,data:null,source:"notion",generatedAt:new Date().toISOString(),error:{code:"UPSTREAM_UNAVAILABLE",message:"Canonical source unavailable"}})}));await page.goto(`/os/${scope}/command?mode=${scope==="personal"?"reset":"clients"}`);await expect(page.getByText("Your current operating state could not load.",{exact:true})).toBeVisible();await expect(page.getByText("No replacement data is shown.",{exact:false})).toBeVisible()});
