import { expect, test, type Page } from "@playwright/test";

const personal={identity:{name:"David Craig",context:"Personal Intelligence System"},attention:[{kind:"COMMITMENT",title:"Protect the priority",detail:"Due today",tone:"attention",href:"https://www.notion.so/a"}],focus:{title:"Ship the verified slice",detail:"Complete the current outcome",progress:42,href:"https://www.notion.so/b"},decisions:[{title:"Choose the next move",meta:"HIGH · OPEN",href:"https://www.notion.so/c"}],signals:[{title:"Capacity is improving",meta:"STRONG · POSITIVE",href:"https://www.notion.so/d"}],media:{title:"Focus soundtrack",detail:"DEEP WORK · MUSIC",href:"https://www.notion.so/e"},rhythms:{active:4,attention:1,healthy:3},navigation:[]};
const business={identity:{name:"ProdigyIQ Technologies",context:"Executive Command"},requiresDavid:[{kind:"DECISION",title:"Approve the proposal",detail:"HIGH · IMMEDIATE",tone:"attention",href:"https://www.notion.so/a"}],pulse:[{label:"Active opportunities",value:"1",tone:"healthy"},{label:"Open decisions",value:"1",tone:"attention"},{label:"High / critical exceptions",value:"0",tone:"healthy"},{label:"Active digital workers",value:"2",tone:"neutral"},{label:"Metrics at risk",value:"0",tone:"healthy"},{label:"Production capabilities",value:"1",tone:"healthy"}],worktelli:{generation:"G2",certification:"CERTIFIED",productState:"PRODUCTION",primaryConstraint:"No active constraint",currentPacket:"Qualification",latestQualification:"PASS"},revenue:{activeCount:1,estimatedValue:125000,topOpportunity:{title:"Priority account",detail:"PROPOSAL · $125,000",href:"https://www.notion.so/b"}},workforce:{healthy:2,attention:0,waiting:0,degraded:0,offline:0,totalActive:2},decisions:[{title:"Approve the proposal",meta:"HIGH · IMMEDIATE",href:"https://www.notion.so/a"}],exceptions:[],signals:[{title:"Customer pull",meta:"HIGH · CLIENT",href:"https://www.notion.so/c"}],navigation:[]};
const ok=(data:unknown)=>JSON.stringify({ok:true,data,source:"notion",generatedAt:"2026-09-14T18:00:00.000Z",error:null});
async function mock(page:Page,scope:"personal"|"business",data:unknown){await page.route(`**/api/os/${scope}/command`,route=>route.fulfill({contentType:"application/json",body:ok(data)}))}

for(const [scope,data] of [["personal",personal],["business",business]] as const)for(const width of [320,390,430,768,1024,1440])test(`${scope} command is premium and overflow-safe at ${width}px`,async({page})=>{const messages:string[]=[];page.on("console",message=>{if(["error","warning"].includes(message.type()))messages.push(message.text())});await mock(page,scope,data);await page.setViewportSize({width,height:1000});await page.goto(`/os/${scope}/command`);await expect(page.locator("main.os-shell")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();const actions=page.locator(".os-actions a,.os-actions button,.os-capture a,.os-compact-list a,.os-section-title>a,.os-business-grid a,.os-module-flow a");for(const control of await actions.all()){const box=await control.boundingBox();expect(box).not.toBeNull();expect(box!.height).toBeGreaterThanOrEqual(44);expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(width)}for(const control of await page.locator(".os-mode-rail a").all()){const box=await control.boundingBox();expect(box).not.toBeNull();expect(box!.height).toBeGreaterThanOrEqual(44)}expect(messages).toEqual([])});

for(const [name,changes,expected] of [
  ["normal populated",{},"Protect the priority"],
  ["minimal",{attention:[],decisions:[],signals:[],focus:null,media:null,rhythms:{active:0,attention:0,healthy:0}},"Nothing currently requires attention."],
  ["no attention",{attention:[]},"Nothing currently requires attention."],
  ["no focus",{focus:null},"No current focus selected."],
  ["no media",{media:null},"No current media"],
  ["open decisions",{decisions:personal.decisions},"Choose the next move"],
  ["signals present",{signals:personal.signals},"Capacity is improving"]
] as const)test(`personal state: ${name}`,async({page})=>{await mock(page,"personal",{...personal,...changes});await page.goto("/os/personal/command");await expect(page.getByText(expected,{exact:true}).first()).toBeVisible()});

for(const [name,changes,expected] of [
  ["empty",{requiresDavid:[],decisions:[],exceptions:[],signals:[],revenue:{activeCount:0,estimatedValue:0,topOpportunity:null},workforce:{healthy:0,attention:0,waiting:0,degraded:0,offline:0,totalActive:0}},"No executive decisions or exceptions require attention."],
  ["decisions only",{requiresDavid:business.requiresDavid,decisions:business.decisions,exceptions:[]},"Approve the proposal"],
  ["exceptions only",{requiresDavid:[{kind:"EXCEPTION",title:"Production constraint",detail:"HIGH · TRIAGE",tone:"critical",href:"https://www.notion.so/e"}],decisions:[],exceptions:[{kind:"EXCEPTION",title:"Production constraint",detail:"HIGH · TRIAGE",tone:"critical",href:"https://www.notion.so/e"}]},"Production constraint"],
  ["Worktelli",{worktelli:business.worktelli},"PRODUCTION"],
  ["revenue",{revenue:business.revenue},"Priority account"],
  ["workforce",{workforce:business.workforce},"2 active"],
  ["mixed",{},"Customer pull"]
] as const)test(`business state: ${name}`,async({page})=>{await mock(page,"business",{...business,...changes});await page.goto("/os/business/command");await expect(page.getByText(expected,{exact:true}).first()).toBeVisible()});

for(const scope of ["personal","business"] as const)test(`${scope} API failure never substitutes fixture data`,async({page})=>{await page.route(`**/api/os/${scope}/command`,route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({ok:false,data:null,source:"notion",generatedAt:new Date().toISOString(),error:{code:"UPSTREAM_UNAVAILABLE",message:"Canonical source unavailable"}})}));await page.goto(`/os/${scope}/command`);await expect(page.getByText("Unable to load current operating state.",{exact:true})).toBeVisible();await expect(page.getByText("Canonical data was not replaced.",{exact:false})).toBeVisible()});
