import { expect, test } from "@playwright/test";

const routes=["clock","focus","session","mode","media","quick-capture","executive-pulse","worktelli-state","exception","header"];
const widths=[320,390,768,1024];

for(const route of routes) for(const width of widths) test(`${route} is embed-safe at ${width}px`,async({page})=>{
  const errors:string[]=[];page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});
  await page.setViewportSize({width,height:720});await page.goto(`/widgets/${route}`);await expect(page.locator("main")).toBeVisible();
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);
  expect(overflow).toBeFalsy();expect(errors).toEqual([]);
});

test("clock renders Central time and compact mode",async({page})=>{await page.goto("/widgets/clock?compact=true");await expect(page.locator(".clock-time")).toContainText(/\d{1,2}:\d{2}/);await expect(page.locator("main")).toHaveAttribute("data-theme","compact")});
test("focus presets, custom input, controls, and reset are deterministic",async({page})=>{await page.goto("/widgets/focus");await page.getByRole("button",{name:"50 min"}).click();await expect(page.locator(".timer-readout")).toHaveText("50:00");await page.getByLabel("Custom minutes").fill("2");await page.getByRole("button",{name:"Set",exact:true}).click();await expect(page.locator(".timer-readout")).toHaveText("02:00");await page.getByRole("button",{name:"Start",exact:true}).click();await page.waitForTimeout(1100);await expect(page.locator(".timer-readout")).not.toHaveText("02:00");await page.getByRole("button",{name:"Pause"}).click();await page.getByRole("button",{name:"Resume"}).click();await page.getByRole("button",{name:"End"}).click();await expect(page.locator(".timer-readout")).toHaveText("00:00");await page.getByRole("button",{name:"Reset"}).click();await expect(page.locator(".timer-readout")).toHaveText("02:00")});
test("session transitions and resets",async({page})=>{await page.goto("/widgets/session");await page.getByLabel("Objective").fill("Ship the verified slice");await page.getByRole("button",{name:"Begin"}).click();await expect(page.getByText("ACTIVE",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Pause"}).click();await expect(page.getByText("PAUSED",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Complete"}).click();await expect(page.getByText("COMPLETE",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Reset"}).click();await expect(page.getByText("IDLE",{exact:true})).toBeVisible()});
test("all operating modes are reachable without dead anchors",async({page})=>{await page.goto("/widgets/mode");expect(await page.locator(".mode-grid a").count()).toBe(6);for(const a of await page.locator(".mode-grid a").all())expect(await a.getAttribute("href")).toMatch(/^https:\/\/www\.notion\.so\//);await page.getByRole("button",{name:"Business"}).click();expect(await page.locator(".mode-grid a").count()).toBe(6)});
test("media has no autoplay and only one selected context",async({page})=>{await page.goto("/widgets/media");expect(await page.locator("audio[autoplay],video[autoplay]").count()).toBe(0);await page.getByRole("button",{name:"Podcast"}).click();expect(await page.locator('button[aria-pressed="true"]').count()).toBe(1);await expect(page.getByRole("button",{name:"Open provider"})).toBeDisabled()});
test("quick capture destinations resolve as links and expose no write request",async({page})=>{const requests:string[]=[];page.on("request",r=>{if(r.method()!=="GET")requests.push(`${r.method()} ${r.url()}`)});await page.goto("/widgets/quick-capture");expect(await page.locator(".capture-grid a").count()).toBe(6);await page.getByRole("button",{name:"Business"}).click();expect(await page.locator(".capture-grid a").count()).toBe(5);expect(requests).toEqual([])});
test("data widgets expose safe disabled state without credentials",async({page})=>{for(const route of ["executive-pulse","worktelli-state","exception"]){await page.goto(`/widgets/${route}`);await expect(page.getByText("DISABLED",{exact:true})).toBeVisible()}});
test("all controls have accessible names and keyboard focus",async({page})=>{for(const route of routes){await page.goto(`/widgets/${route}`);const controls=page.locator("button,a,input");for(const control of await controls.all()){expect((await control.getAttribute("aria-label"))||(await control.textContent())||(await control.getAttribute("id"))).toBeTruthy()}if(await controls.count()){await page.keyboard.press("Tab");expect(await page.locator(":focus-visible").count()).toBeGreaterThan(0)}}});
