import { expect, test } from "@playwright/test";

const routes=["clock","focus","session","mode","media","quick-capture","executive-pulse","worktelli-state","exception","header","countdown","alignment","progress","attention","health-matrix","workforce-status","opportunity-radar","decision-queue","daily-brief","weekly-review"];
const widths=[320,390,768,1024];

for(const route of routes) for(const width of widths) test(`${route} is embed-safe at ${width}px`,async({page})=>{
  const errors:string[]=[];page.on("console",message=>{if(message.type()==="error"||message.type()==="warning")errors.push(message.text())});
  await page.setViewportSize({width,height:720});await page.goto(`/widgets/${route}`);await expect(page.locator("main")).toBeVisible();
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);
  expect(overflow).toBeFalsy();expect(errors).toEqual([]);
});

test("clock renders Central time and compact mode",async({page})=>{await page.goto("/widgets/clock?compact=true");await expect(page.locator(".clock-time")).toContainText(/\d{1,2}:\d{2}/);await expect(page.locator("main")).toHaveAttribute("data-theme","compact")});
test("focus presets, custom input, controls, and reset are deterministic",async({page})=>{await page.goto("/widgets/focus");await page.getByRole("button",{name:"50 min"}).click();await expect(page.locator(".timer-readout")).toHaveText("50:00");await page.getByLabel("Custom minutes").fill("2");await page.getByRole("button",{name:"Set",exact:true}).click();await expect(page.locator(".timer-readout")).toHaveText("02:00");await page.getByRole("button",{name:"Start",exact:true}).click();await page.waitForTimeout(1100);await expect(page.locator(".timer-readout")).not.toHaveText("02:00");await page.getByRole("button",{name:"Pause"}).click();await page.getByRole("button",{name:"Resume"}).click();await page.getByRole("button",{name:"End"}).click();await expect(page.locator(".timer-readout")).toHaveText("00:00");await page.getByRole("button",{name:"Reset"}).click();await expect(page.locator(".timer-readout")).toHaveText("02:00")});
test("session transitions and resets",async({page})=>{await page.goto("/widgets/session");await page.getByLabel("Objective").fill("Ship the verified slice");await page.getByRole("button",{name:"Begin"}).click();await expect(page.getByText("ACTIVE",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Pause"}).click();await expect(page.getByText("PAUSED",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Complete"}).click();await expect(page.getByText("COMPLETE",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Reset"}).click();await expect(page.getByText("IDLE",{exact:true})).toBeVisible()});
test("all operating modes are reachable without dead anchors",async({page})=>{await page.goto("/widgets/mode");expect(await page.locator(".mode-grid a").count()).toBe(6);for(const a of await page.locator(".mode-grid a").all())expect(await a.getAttribute("href")).toMatch(/^https:\/\/www\.notion\.so\//);await page.getByRole("button",{name:"Business"}).click();expect(await page.locator(".mode-grid a").count()).toBe(6)});
test("media keeps one active public provider with no autoplay",async({page})=>{await page.route("**/api/widgets/media**",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,data:{items:[{id:"one",title:"Focus film",mediaType:"VIDEO",platform:"YouTube",url:"https://youtu.be/abc123XYZ",mode:"DEEP WORK",purpose:"Focus",duration:20,favorite:true,provider:"youtube",embedUrl:"https://www.youtube-nocookie.com/embed/abc123XYZ"},{id:"two",title:"Reference",mediaType:"REFERENCE",platform:"Web",url:"https://example.com/reference",mode:"WRITING",purpose:"Draft",duration:null,favorite:false,provider:"external",embedUrl:null}]},generatedAt:new Date().toISOString()})}));await page.goto("/widgets/media?mode=deep-work");expect(await page.locator("audio[autoplay],video[autoplay]").count()).toBe(0);await expect(page.getByText("EXTERNAL PROVIDER",{exact:true})).toBeVisible();await expect(page.locator("iframe")).toHaveCount(1);await page.getByRole("button",{name:"Next"}).click();await expect(page.locator("iframe,audio")).toHaveCount(0);await expect(page.getByRole("link",{name:/Open in provider/})).toHaveAttribute("href","https://example.com/reference")});
test("direct audio exposes truthful ready, playing, and paused states",async({page})=>{await page.route("**/api/widgets/media**",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,data:{items:[{id:"audio",title:"Focus audio",mediaType:"AUDIO",platform:"Direct",url:"https://media.example.com/focus.mp3",mode:"DEEP WORK",purpose:"Focus",duration:30,favorite:false,provider:"direct-audio",embedUrl:null}]},generatedAt:new Date().toISOString()})}));await page.goto("/widgets/media");await expect(page.getByText("READY",{exact:true})).toBeVisible();const audio=page.locator("audio");await audio.dispatchEvent("play");await expect(page.getByText("PLAYING",{exact:true})).toBeVisible();await audio.dispatchEvent("pause");await expect(page.getByText("PAUSED",{exact:true})).toBeVisible();expect(await page.locator("audio[autoplay]").count()).toBe(0)});
test("media reports unavailable and source errors without broken players",async({page})=>{await page.route("**/api/widgets/media**",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({ok:true,data:{items:[{id:"missing",title:"Missing URL",mediaType:"AUDIO",platform:"Unknown",url:null,mode:"DEEP WORK",purpose:"",duration:null,provider:"unavailable",embedUrl:null}]},generatedAt:new Date().toISOString()})}));await page.goto("/widgets/media");await expect(page.getByText("UNAVAILABLE",{exact:true})).toBeVisible();await expect(page.locator("iframe,audio")).toHaveCount(0);await page.unroute("**/api/widgets/media**");await page.route("**/api/widgets/media**",route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({ok:false,data:null,error:{code:"UPSTREAM_UNAVAILABLE",message:"P11 unavailable"},generatedAt:new Date().toISOString()})}));await page.reload();await expect(page.getByText("ERROR",{exact:true})).toBeVisible()});
test("quick capture destinations resolve as links and expose no write request",async({page})=>{const requests:string[]=[];page.on("request",r=>{if(r.method()!=="GET")requests.push(`${r.method()} ${r.url()}`)});await page.goto("/widgets/quick-capture");expect(await page.locator(".capture-grid a").count()).toBe(6);await page.getByRole("button",{name:"Business"}).click();expect(await page.locator(".capture-grid a").count()).toBe(5);expect(requests).toEqual([])});
test("data widgets expose a truthful configured or disabled state",async({page},testInfo)=>{const local=String(testInfo.project.use.baseURL).includes("127.0.0.1");for(const route of ["executive-pulse","worktelli-state","exception","health-matrix","workforce-status","opportunity-radar","decision-queue","daily-brief"]){await page.goto(`/widgets/${route}`);if(local)await expect(page.getByText("DISABLED",{exact:true})).toBeVisible();else{await expect(page.getByText("ERROR",{exact:true})).toHaveCount(0);await expect(page.locator("footer")).toBeVisible()}}});
test("wave 2 local widgets disclose fixture or local truth",async({page})=>{for(const route of ["alignment","attention","weekly-review"]){await page.goto(`/widgets/${route}`);await expect(page.getByText(/FIXTURE DATA/).first()).toBeVisible()}for(const route of ["countdown","progress"]){await page.goto(`/widgets/${route}`);await expect(page.locator("footer")).toContainText(/Local/)}await page.goto("/widgets/daily-brief?mode=personal-shell");await expect(page.getByText("FIXTURE LAYOUT · PERSONAL READS 0")).toBeVisible()});
test("wave 2 forced states stay explicit",async({page})=>{for(const state of ["loading","empty","error","disabled"]){await page.goto(`/widgets/progress?context=${state}`);await expect(page.getByText(state.toUpperCase(),{exact:true})).toBeVisible()}});
test("all controls have accessible names and keyboard focus",async({page})=>{for(const route of routes){await page.goto(`/widgets/${route}`);const controls=page.locator("button,a,input");for(const control of await controls.all()){expect((await control.getAttribute("aria-label"))||(await control.textContent())||(await control.getAttribute("id"))).toBeTruthy()}if(await controls.count()){await page.keyboard.press("Tab");expect(await page.locator(":focus-visible").count()).toBeGreaterThan(0)}}});
