import assert from "node:assert/strict";
import test from "node:test";
import type { NotionRow } from "../lib/notion-values";
import { alignmentStatus, attentionValidation, clampProgress, countdownParts, deltaStatus, deriveDailyBrief, deriveDecisionQueue, deriveOpportunityRadar, deriveWorkforceStatus } from "../lib/widget-data/wave2";

function row(values:Record<string,string|number|boolean|string[]>):NotionRow{const properties:NotionRow["properties"]={};for(const [name,value] of Object.entries(values)){if(Array.isArray(value))properties[name]={type:"relation",relation:value.map(id=>({id}))};else if(typeof value==="boolean")properties[name]={type:"checkbox",checkbox:value};else if(typeof value==="number")properties[name]={type:"number",number:value};else if(["Opportunity","Decision","Exception","Digital Worker","Capability"].includes(name))properties[name]={type:"title",title:[{plain_text:value}]};else if(name==="Date Opened")properties[name]={type:"date",date:{start:value}};else properties[name]={type:"select",select:{name:value}}}return{id:crypto.randomUUID(),properties}}

test("countdown covers future, reached, past, invalid, and minute boundary",()=>{const now=1_000_000;assert.deepEqual(countdownParts(now+86_400_000+3_600_000+60_000,now),{total:90_060_000,complete:false,days:1,hours:1,minutes:1});assert.equal(countdownParts(now,now)?.complete,true);assert.equal(countdownParts(now-1,now)?.total,0);assert.equal(countdownParts(Number.NaN,now),null);assert.equal(countdownParts(now+59_999,now)?.minutes,0);assert.equal(countdownParts(now+60_000,now)?.minutes,1)});
test("alignment thresholds and progress clamps are exact",()=>{assert.equal(alignmentStatus(85),"HEALTHY");assert.equal(alignmentStatus(70),"ATTENTION");assert.equal(alignmentStatus(50),"HIGH RISK");assert.equal(alignmentStatus(49),"CRITICAL");assert.deepEqual([-2,0,1,50,99,100,101].map(clampProgress),[0,0,1,50,99,100,100])});
test("attention totals disclose invalid allocation",()=>{assert.match(attentionValidation(99),/REVIEW/);assert.equal(attentionValidation(100),"TARGET ALLOCATION VALID");assert.match(attentionValidation(101),/REVIEW/)});
test("workforce excludes retired and classifies mixed and zero states",()=>{assert.equal(deriveWorkforceStatus([]).totalActive,0);assert.deepEqual(deriveWorkforceStatus([row({Status:"ACTIVE",Health:"HEALTHY"})]),{healthy:1,attention:0,waiting:0,degraded:0,offline:0,totalActive:1});const mixed=deriveWorkforceStatus([row({Status:"ACTIVE",Health:"ATTENTION"}),row({Status:"ACTIVE",Health:"WAITING"}),row({Status:"ACTIVE",Health:"DEGRADED"}),row({Status:"ACTIVE",Health:"OFFLINE"}),row({Status:"RETIRED",Health:"HEALTHY"})]);assert.deepEqual(mixed,{healthy:0,attention:1,waiting:1,degraded:1,offline:1,totalActive:4})});
test("opportunity radar filters LOST and ranks score then value",()=>{const items=deriveOpportunityRadar([row({Opportunity:"Low",Stage:"OPEN","Opportunity Score":50,"Estimated Value":1000}),row({Opportunity:"Tie high value",Stage:"OPEN","Opportunity Score":80,"Estimated Value":2000,Company:["c1"]}),row({Opportunity:"Tie low value",Stage:"OPEN","Opportunity Score":80,"Estimated Value":1000}),row({Opportunity:"No value",Stage:"OPEN","Opportunity Score":90}),row({Opportunity:"Lost",Stage:"LOST","Opportunity Score":100})]);assert.deepEqual(items.map(item=>item.opportunity),["No value","Tie high value","Tie low value","Low"]);assert.equal(items[1].company,"LINKED COMPANY");assert.equal(items[0].estimatedValue,null)});
test("decision queue filters and sorts impact, urgency, then oldest",()=>{const now=new Date("2026-09-14T00:00:00Z");const items=deriveDecisionQueue([row({Decision:"Medium",Status:"OPEN",Impact:"MEDIUM",Urgency:"NORMAL","Date Opened":"2026-09-01"}),row({Decision:"Old high",Status:"REVIEWING",Impact:"HIGH",Urgency:"HIGH","Date Opened":"2026-08-01"}),row({Decision:"New high",Status:"OPEN",Impact:"HIGH",Urgency:"HIGH","Date Opened":"2026-09-10"}),row({Decision:"Closed",Status:"CLOSED",Impact:"CRITICAL",Urgency:"IMMEDIATE"})],now);assert.deepEqual(items.map(item=>item.decision),["Old high","New high","Medium"])});
test("daily brief is deterministic for empty and mixed canonical inputs",()=>{const empty={B03:[],B05:[],B07:[],B08:[],B10:[]};assert.deepEqual(deriveDailyBrief(empty).items,["0 open decisions","0 high-severity exceptions","No live opportunities populated","Worktelli state not yet populated","0 workforce items need attention"]);const mixed=deriveDailyBrief({...empty,B03:[row({Opportunity:"Pipeline",Stage:"OPEN","Opportunity Score":90})],B05:[row({Decision:"Choose",Status:"OPEN",Impact:"HIGH"})],B07:[row({Exception:"Risk",Severity:"CRITICAL",Status:"OPEN"})],B08:[row({Status:"ACTIVE",Health:"DEGRADED"})],B10:[row({Capability:"Core",Maturity:"PRODUCTION"})]}).items;assert.match(mixed[0],/^1 open decision$/);assert.match(mixed[1],/^1 high-severity exception$/);assert.equal(mixed[2],"Top opportunity: Pipeline");assert.equal(mixed[3],"Worktelli state: PRODUCTION");assert.match(mixed[4],/^1 workforce item needs attention$/)});
test("weekly deltas cover positive, negative, flat, missing prior, and unknown",()=>{assert.deepEqual(deltaStatus(2,1),{delta:1,status:"UP"});assert.deepEqual(deltaStatus(1,2),{delta:-1,status:"DOWN"});assert.deepEqual(deltaStatus(1,1),{delta:0,status:"FLAT"});assert.deepEqual(deltaStatus(1,null),{delta:null,status:"NO PRIOR"});assert.deepEqual(deltaStatus(null,1),{delta:null,status:"UNKNOWN"})});
