"use client";

import { useCallback, useEffect, useState } from "react";
import type { BusinessCommandData, PersonalCommandData } from "@/lib/os-data/types";
import { LiveContext } from "@/components/os/live-context";

type Envelope<T>={ok:true;data:T;generatedAt:string}|{ok:false;data:null;generatedAt:string;error:{code:string;message:string}};
type LoadState<T>={state:"loading"}|{state:"error";detail:string}|{state:"ready";data:T;generatedAt:string};

const notion={
 personalCommand:"https://www.notion.so/3da42c9f9e5f8107a4b7d4056fa6d8ff",businessCommand:"https://www.notion.so/3da42c9f9e5f81ca95c2c17aa2470cca",
 today:"https://www.notion.so/3da42c9f9e5f8161a132d3fc348d050c",focus:"https://www.notion.so/3da42c9f9e5f8174a46be4bbf198497d",spiritual:"https://www.notion.so/3da42c9f9e5f81b681e2ea1b47674c1b",brand:"https://www.notion.so/3da42c9f9e5f81e7aad9ef24244b6c82",growth:"https://www.notion.so/3da42c9f9e5f81f2b73df164fa9f0722",reset:"https://www.notion.so/3da42c9f9e5f819ca5a6ec72b0cd2c1c",
 revenue:"https://www.notion.so/3da42c9f9e5f81569dfeeb41ea185a5c",worktelli:"https://www.notion.so/3da42c9f9e5f81ff9582cbc1edc7d00e",engineering:"https://www.notion.so/3da42c9f9e5f811ab596d16e08496ec8",clients:"https://www.notion.so/3da42c9f9e5f819fbadec40c7e9fd976",workforce:"https://www.notion.so/3da42c9f9e5f8155b6abebca2bc35536",
 prayer:"https://www.notion.so/a2e100b81b534d9daf930c442c00281c",personalDecision:"https://www.notion.so/4c11a712c39a4176ba7a41a8a96c236c",brandIdea:"https://www.notion.so/fc7b4765360e47b48d6063f3837038ee",knowledge:"https://www.notion.so/e7075ed9959141d89382b515a0c09397",commitment:"https://www.notion.so/fc64e6a23d2a4065a28a6da487f23a67",personalSignal:"https://www.notion.so/b37baae9772d4581b39149217c142050",
 opportunity:"https://www.notion.so/4955ac345ac748e3b54128019a0a716a",businessSignal:"https://www.notion.so/3ce532354e3b4dd2891608083f988005",businessDecision:"https://www.notion.so/bbbee0957be8415ca52332df564bd85d",exception:"https://www.notion.so/87983ed749614694ba6bd0f0dfc6b586",initiative:"https://www.notion.so/2d3d81c2e6544444a8ae92ee4a6590bd"
} as const;
const personalModes=[["COMMAND",notion.personalCommand],["FOCUS",notion.focus],["SPIRITUAL",notion.spiritual],["BRAND",notion.brand],["GROWTH",notion.growth],["RESET",notion.reset]] as const;
const businessModes=[["EXECUTIVE",notion.businessCommand],["REVENUE",notion.revenue],["WORKTELLI",notion.worktelli],["ENGINEERING",notion.engineering],["CLIENTS",notion.clients],["WORKFORCE",notion.workforce]] as const;

function useCommandData<T>(path:string){
  const [result,setResult]=useState<LoadState<T>>({state:"loading"});
  const load=useCallback(()=>{const controller=new AbortController();fetch(path,{cache:"no-store",signal:controller.signal}).then(async response=>({response,body:await response.json() as Envelope<T>})).then(({body})=>body.ok?setResult({state:"ready",data:body.data,generatedAt:body.generatedAt}):setResult({state:"error",detail:body.error.message})).catch(error=>{if(error.name!=="AbortError")setResult({state:"error",detail:"Unable to load current operating state."})});return()=>controller.abort()},[path]);
  useEffect(()=>load(),[load]);const retry=useCallback(()=>{setResult({state:"loading"});load()},[load]);return {result,retry};
}

function ModeRail({items,current}:{items:readonly (readonly [string,string])[];current:string}){return <nav className="os-mode-rail" aria-label="Operating modes">{items.map(([label,href])=><a key={label} href={href} target="_blank" rel="noreferrer" aria-current={label===current?"page":undefined}>{label}</a>)}</nav>}
function ShellLoading(){return <div className="os-loading" role="status" aria-busy="true"><span/><span/><span/><span/></div>}
function ShellError({detail,retry,href}:{detail:string;retry:()=>void;href:string}){return <section className="os-error" role="alert"><p className="os-eyebrow">CANONICAL CONNECTION</p><h2>Unable to load current operating state.</h2><p>{detail} Canonical data was not replaced.</p><div className="os-actions"><button onClick={retry}>Retry</button><a href={href} target="_blank" rel="noreferrer">Open Notion ↗</a></div></section>}
function SectionTitle({eyebrow,title,action}:{eyebrow:string;title:string;action?:{label:string;href:string}}){return <header className="os-section-title"><div><p className="os-eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action?<a href={action.href} target="_blank" rel="noreferrer">{action.label} ↗</a>:null}</header>}
function CompactList({items,empty}:{items:Array<{title:string;meta?:string;detail?:string;href:string;tone?:string}>;empty:string}){return items.length?<div className="os-compact-list">{items.map((item,index)=><a href={item.href} target="_blank" rel="noreferrer" key={`${item.title}-${index}`} data-tone={item.tone}><strong>{item.title}</strong><span>{item.meta??item.detail}</span></a>)}</div>:<p className="os-empty">{empty}</p>}
function Freshness({at}:{at:string}){return <span className="os-fresh">Live canonical state · {new Date(at).toLocaleTimeString("en-US",{timeZone:"America/Chicago",hour:"numeric",minute:"2-digit"})} CT</span>}

export function PersonalCommandShell(){const {result,retry}=useCommandData<PersonalCommandData>("/api/os/personal/command");return <main className="os-shell os-personal">
  <header className="os-header"><div><p className="os-eyebrow">CRAIG OS · PERSONAL</p><h1>David Command</h1><p>Operate with alignment. Protect what matters.</p></div><LiveContext personal/></header>
  <ModeRail items={personalModes} current="COMMAND"/>
  {result.state==="loading"?<ShellLoading/>:result.state==="error"?<ShellError detail={result.detail} retry={retry} href={notion.personalCommand}/>:<>
    <section className="os-hero-grid"><div className="os-primary"><SectionTitle eyebrow="TODAY" title="Requires attention" action={{label:"Daily focus",href:notion.today}}/><CompactList items={result.data.attention} empty="Nothing currently requires attention."/></div><div className="os-focus"><p className="os-eyebrow">CURRENT FOCUS</p>{result.data.focus?<><h2>{result.data.focus.title}</h2><p>{result.data.focus.detail}</p>{result.data.focus.progress!==null?<div className="os-progress"><span style={{width:`${Math.max(0,Math.min(100,result.data.focus.progress))}%`}}/></div>:null}<a href={result.data.focus.href} target="_blank" rel="noreferrer">Open outcome ↗</a></>:<><h2>No current focus selected.</h2><p>Open the Focus surface to choose a canonical NOW outcome.</p></>}<div className="os-actions"><a className="os-primary-action" href="/widgets/focus?theme=personal&mode=focus">Open focus timer</a><a href={notion.focus} target="_blank" rel="noreferrer">Focus workspace ↗</a></div></div></section>
    <section className="os-capture"><SectionTitle eyebrow="QUICK CAPTURE" title="Keep the thought. Stay in motion."/><div>{[["Prayer",notion.prayer],["Decision",notion.personalDecision],["Brand Idea",notion.brandIdea],["Insight",notion.knowledge],["Commitment",notion.commitment],["Signal",notion.personalSignal]].map(([label,href])=><a key={label} href={href} target="_blank" rel="noreferrer">+ {label}</a>)}</div><p>Safe deep links open the canonical Notion destination. No custom write API.</p></section>
    <section className="os-module-flow"><div><SectionTitle eyebrow="MEDIA" title={result.data.media?.title??"No current media"} action={{label:"Media controller",href:"/widgets/media?mode=deep-work&theme=personal"}}/><p>{result.data.media?.detail??"No focus, spiritual, learning, or brand media is currently populated."}</p>{result.data.media?<a href={result.data.media.href} target="_blank" rel="noreferrer">Open media record ↗</a>:null}</div><div><SectionTitle eyebrow="RHYTHMS / CAPACITY" title={`${result.data.rhythms.active} active rhythms`} action={{label:"Review",href:notion.reset}}/><dl className="os-metrics"><div><dt>Healthy</dt><dd>{result.data.rhythms.healthy}</dd></div><div><dt>Attention</dt><dd>{result.data.rhythms.attention}</dd></div></dl></div></section>
    <section className="os-split"><div><SectionTitle eyebrow="OPEN DECISIONS" title="Decision review" action={{label:"All decisions",href:notion.personalDecision}}/><CompactList items={result.data.decisions} empty="No open decisions require attention."/></div><div><SectionTitle eyebrow="NOTABLE SIGNALS" title="Material patterns" action={{label:"All signals",href:notion.personalSignal}}/><CompactList items={result.data.signals} empty="No notable signals are currently populated."/></div></section><Freshness at={result.generatedAt}/>
  </>}
  <footer className="os-footer"><span>Craig OS v0.5.0</span><span>Read-only command shell · America/Chicago</span></footer>
  </main>}

export function BusinessCommandShell(){const {result,retry}=useCommandData<BusinessCommandData>("/api/os/business/command");return <main className="os-shell os-business">
  <header className="os-header"><div><p className="os-eyebrow">PRODIGYIQ TECHNOLOGIES</p><h1>Executive Command</h1><p>Make the next clear decision.</p></div><LiveContext/></header>
  <ModeRail items={businessModes} current="EXECUTIVE"/>
  {result.state==="loading"?<ShellLoading/>:result.state==="error"?<ShellError detail={result.detail} retry={retry} href={notion.businessCommand}/>:<>
    <section className="os-requires"><SectionTitle eyebrow="REQUIRES DAVID" title="Executive attention"/><CompactList items={result.data.requiresDavid} empty="No executive decisions or exceptions require attention."/></section>
    <section className="os-business-grid"><article><p className="os-eyebrow">WORKTELLI</p><h2>{result.data.worktelli.productState}</h2><p>{result.data.worktelli.generation} · {result.data.worktelli.certification}</p><span>{result.data.worktelli.primaryConstraint}</span><a href={notion.worktelli} target="_blank" rel="noreferrer">Open product control ↗</a></article><article><p className="os-eyebrow">REVENUE</p><h2>{result.data.revenue.activeCount} active</h2><p>{new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(result.data.revenue.estimatedValue)} canonical pipeline</p><span>{result.data.revenue.topOpportunity?.title??"No live opportunity populated"}</span><a href={result.data.revenue.topOpportunity?.href??notion.revenue} target="_blank" rel="noreferrer">Open revenue command ↗</a></article><article><p className="os-eyebrow">WORKFORCE</p><h2>{result.data.workforce.totalActive} active</h2><p>{result.data.workforce.healthy} healthy · {result.data.workforce.degraded+result.data.workforce.waiting+result.data.workforce.attention+result.data.workforce.offline} attention</p><span>{result.data.workforce.offline} offline</span><a href={notion.workforce} target="_blank" rel="noreferrer">Open workforce control ↗</a></article></section>
    <section className="os-pulse"><SectionTitle eyebrow="EXECUTIVE PULSE" title="Operating state"/><dl className="os-pulse-line">{result.data.pulse.map(item=><div key={item.label}><dt>{item.label}</dt><dd data-tone={item.tone}>{item.value}</dd></div>)}</dl></section>
    <section className="os-split"><div><SectionTitle eyebrow="OPEN DECISIONS" title="Decision queue" action={{label:"Business decisions",href:notion.businessDecision}}/><CompactList items={result.data.decisions} empty="No open business decisions."/></div><div><SectionTitle eyebrow="INTELLIGENCE" title="Material signals" action={{label:"Signal registry",href:notion.businessSignal}}/><CompactList items={result.data.signals} empty="No material business signals are currently populated."/></div></section>
    <section className="os-split"><div><SectionTitle eyebrow="OPEN EXCEPTIONS" title="Constraint watch" action={{label:"Exception center",href:notion.exception}}/><CompactList items={result.data.exceptions} empty="No active exceptions."/></div><div className="os-capture"><SectionTitle eyebrow="QUICK ACTIONS" title="Open canonical workflow"/><div>{[["Opportunity",notion.opportunity],["Signal",notion.businessSignal],["Decision",notion.businessDecision],["Initiative",notion.initiative],["Exception",notion.exception]].map(([label,href])=><a key={label} href={href} target="_blank" rel="noreferrer">+ {label}</a>)}</div><p>Safe deep links only. No custom write API.</p></div></section><Freshness at={result.generatedAt}/>
  </>}
  <footer className="os-footer"><span>Craig OS v0.5.0</span><span>Read-only executive shell · America/Chicago</span></footer>
  </main>}
