"use client";

import { useCallback, useEffect, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import type { BusinessCommandData, PersonalCommandData } from "@/lib/os-data/types";
import { businessModeRegistry, businessModes, notion, parseBusinessMode, parsePersonalMode, personalModeRegistry, personalModes, type BusinessMode, type ModeAction, type ModeDefinition, type OperatingMode, type PersonalMode } from "@/lib/os-data/modes";
import { LiveContext } from "@/components/os/live-context";
import { MediaTheater } from "@/components/os/media-theater";
import { ActionButton } from "@/components/actions/action-layer";
import { DetailDrawerTrigger, type DetailRecord } from "@/components/os/detail-drawer";
import type { ActionScope } from "@/lib/actions/registry";

type Envelope<T>={ok:true;data:T;generatedAt:string}|{ok:false;data:null;generatedAt:string;error:{code:string;message:string}};
type LoadState<T>={state:"loading"}|{state:"error";detail:string}|{state:"ready";data:T;generatedAt:string};

function useCommandData<T>(path:string,scope:ActionScope){
  const [result,setResult]=useState<LoadState<T>>({state:"loading"});
  const load=useCallback(()=>{const controller=new AbortController();fetch(path,{cache:"no-store",signal:controller.signal}).then(async response=>await response.json() as Envelope<T>).then(body=>body.ok?setResult({state:"ready",data:body.data,generatedAt:body.generatedAt}):setResult({state:"error",detail:body.error.message})).catch(error=>{if(error.name!=="AbortError")setResult({state:"error",detail:"Unable to load current operating state."})});return()=>controller.abort()},[path]);
  useEffect(()=>load(),[load]);
  useEffect(()=>{const refresh=(event:Event)=>{const detail=(event as CustomEvent<{scope?:ActionScope}>).detail;if(detail?.scope===scope)load()};window.addEventListener("craig-os:action-created",refresh);return()=>window.removeEventListener("craig-os:action-created",refresh)},[load,scope]);
  const retry=useCallback(()=>{setResult({state:"loading"});load()},[load]);return {result,retry};
}

function ModeRail<T extends OperatingMode>({modes,current,registry}:{modes:T[];current:T;registry:Record<T,ModeDefinition<T>>}){
  const router=useRouter(),pathname=usePathname();
  return <nav className="os-mode-rail" aria-label="Operating modes">{modes.map(mode=>{const href=`${pathname}?mode=${mode}`;return <a key={mode} href={href} aria-current={mode===current?"page":undefined} onClick={event=>{event.preventDefault();if(mode!==current)router.push(href)}}>{registry[mode].label}</a>})}</nav>;
}
function OsSwitcher({scope}:{scope:"personal"|"business"}){return <nav className="os-context-switch" aria-label="Operating system"><a href="/os/personal?mode=command" aria-current={scope==="personal"?"page":undefined}>Personal</a><a href="/os/business?mode=executive" aria-current={scope==="business"?"page":undefined}>ProdigyIQ</a></nav>}
function ShellLoading(){return <div className="os-loading" role="status" aria-busy="true"><span/><span/><span/><span/></div>}
function ShellError({detail,retry,href}:{detail:string;retry:()=>void;href:string}){return <section className="os-error" role="alert"><p className="os-eyebrow">CANONICAL CONNECTION</p><h2>Unable to load current operating state.</h2><p>{detail} Canonical data was not replaced.</p><div className="os-actions"><button onClick={retry}>Retry</button><a href={href} target="_blank" rel="noreferrer">Open Notion ↗</a></div></section>}
function SectionTitle({eyebrow,title,action}:{eyebrow:string;title:string;action?:{label:string;href:string}}){return <header className="os-section-title"><div><p className="os-eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action?<a href={action.href} target="_blank" rel="noreferrer">{action.label} ↗</a>:null}</header>}
function CompactList({items,empty,type="Record",context="current mode"}:{items:Array<{title:string;meta?:string;detail?:string;href:string;tone?:string;kind?:string}>;empty:string;type?:string;context?:string}){return items.length?<div className="os-compact-list">{items.map((item,index)=>{const record:DetailRecord={title:item.title,type:item.kind??type,status:item.meta??item.detail,summary:item.detail??item.meta,href:item.href,context};return <div key={`${item.title}-${index}`} data-tone={item.tone}><span><strong>{item.title}</strong><small>{item.meta??item.detail}</small></span><DetailDrawerTrigger record={record} label="Inspect"/></div>})}</div>:<p className="os-empty">{empty}</p>}
function Freshness({at}:{at:string}){return <span className="os-fresh">Live canonical state · {new Date(at).toLocaleTimeString("en-US",{timeZone:"America/Chicago",hour:"numeric",minute:"2-digit"})} CT</span>}
function ActionLink({action}:{action:ModeAction}){return action.actionId?<ActionButton actionId={action.actionId} preset={action.preset} label={action.label} className={action.primary?"os-primary-action":undefined}/>:<a className={action.primary?"os-primary-action":undefined} href={action.href} target={action.href.startsWith("?")?undefined:"_blank"} rel={action.href.startsWith("?")?undefined:"noreferrer"}>{action.label}</a>}
function ActionTray({definition}:{definition:ModeDefinition<OperatingMode>}){return <section className="os-mode-actions" aria-label={`${definition.label} actions`}><div><p className="os-eyebrow">PRIMARY ACTION</p><ActionLink action={definition.primaryAction}/></div><div className="os-actions">{definition.secondaryActions.map(action=><ActionLink key={action.label} action={action}/>)}</div></section>}
function ModeIntro({definition}:{definition:ModeDefinition<OperatingMode>}){return <section className="os-mode-intro"><div><p className="os-eyebrow">{definition.label} MODE</p><h2>{definition.heading}</h2><p>{definition.subheading}</p></div><a href={definition.navigation.href} target="_blank" rel="noreferrer">Open in Notion ↗</a></section>}
function ModuleCard({eyebrow,title,body,href,label}:{eyebrow:string;title:string;body:string;href?:string;label?:string}){return <article className="os-module-card"><p className="os-eyebrow">{eyebrow}</p><h3>{title}</h3><p>{body}</p>{href?<a href={href} target={href.startsWith("?")?undefined:"_blank"} rel={href.startsWith("?")?undefined:"noreferrer"}>{label??"Open in Notion"}{href.startsWith("?")?"":" ↗"}</a>:null}</article>}
function ToolFrame({title,src}:{title:string;src:string}){return <div className="os-tool-frame"><iframe title={title} src={src}/></div>}

function PersonalCommand({data}:{data:PersonalCommandData}){return <>
  <section className="os-hero-grid"><div className="os-primary"><SectionTitle eyebrow="TODAY" title="Requires attention" action={{label:"Daily focus",href:notion.today}}/><CompactList items={data.attention} empty="Nothing currently requires attention." type="Personal record" context="Command"/></div><div className="os-focus"><p className="os-eyebrow">CURRENT FOCUS</p>{data.focus?<><h2>{data.focus.title}</h2><p>{data.focus.detail}</p>{data.focus.progress!==null?<div className="os-progress"><span style={{width:`${Math.max(0,Math.min(100,data.focus.progress))}%`}}/></div>:null}<DetailDrawerTrigger label="Inspect outcome" record={{title:data.focus.title,type:"Outcome",status:"NOW",summary:data.focus.detail,href:data.focus.href,context:"Command",properties:[{label:"Progress",value:data.focus.progress===null?null:`${data.focus.progress}%`}]}}/></>:<><h2>No current focus selected.</h2><p>Open the Focus surface to choose a canonical NOW outcome.</p></>}<div className="os-actions"><a className="os-primary-action" href="?mode=focus">Enter Focus mode</a><a href={notion.focus} target="_blank" rel="noreferrer">Open in Notion ↗</a></div></div></section>
  <section className="os-capture"><SectionTitle eyebrow="QUICK CAPTURE" title="Keep the thought. Stay in motion."/><div><a href={notion.prayer} target="_blank" rel="noreferrer">+ Prayer</a><ActionButton actionId="A-P02"/><ActionButton actionId="A-P05"/><ActionButton actionId="A-P04"/><ActionButton actionId="A-P01"/><ActionButton actionId="A-P03"/></div><p>Governed capture writes only to the approved canonical record. Prayer remains native and private.</p></section>
  <section className="os-module-flow"><div><SectionTitle eyebrow="MEDIA" title={data.media?.title??"No current media"} action={{label:"Media controller",href:"/widgets/media?mode=deep-work&theme=personal"}}/><p>{data.media?.detail??"No focus, spiritual, learning, or brand media is currently populated."}</p>{data.media?<a href={data.media.href} target="_blank" rel="noreferrer">Open media record ↗</a>:null}</div><div><SectionTitle eyebrow="RHYTHMS / CAPACITY" title={`${data.rhythms.active} active rhythms`} action={{label:"Review",href:notion.reset}}/><dl className="os-metrics"><div><dt>Healthy</dt><dd>{data.rhythms.healthy}</dd></div><div><dt>Attention</dt><dd>{data.rhythms.attention}</dd></div></dl></div></section>
  <section className="os-split"><div><SectionTitle eyebrow="OPEN DECISIONS" title="Decision review" action={{label:"All decisions",href:notion.personalDecision}}/><CompactList items={data.decisions} empty="No open decisions require attention." type="Decision" context="Command"/></div><div><SectionTitle eyebrow="NOTABLE SIGNALS" title="Material patterns" action={{label:"All signals",href:notion.personalSignal}}/><CompactList items={data.signals} empty="No notable signals are currently populated." type="Signal" context="Command"/></div></section>
</>}

function PersonalModeContent({mode,data}:{mode:PersonalMode;data:PersonalCommandData}){
  const d=personalModeRegistry[mode];
  if(mode==="command")return <PersonalCommand data={data}/>;
  if(mode==="focus")return <><section className="os-focus-experience"><div className="os-objective"><p className="os-eyebrow">CURRENT OBJECTIVE</p><h2>{data.focus?.title??"One clear outcome"}</h2><p>{data.focus?.detail??d.emptyState}</p>{data.focus?<DetailDrawerTrigger label="Inspect outcome" record={{title:data.focus.title,type:"Outcome",status:"NOW",summary:data.focus.detail,href:data.focus.href,context:"Focus",properties:[{label:"Progress",value:data.focus.progress===null?null:`${data.focus.progress}%`}]}}/>:null}</div><ToolFrame title="Focus timer" src="/widgets/focus?theme=personal&compact=true&mode=focus"/></section><MediaTheater mode="focus" embedded/></>;
  if(mode==="spiritual")return <><section className="os-mode-grid"><ModuleCard eyebrow="SCRIPTURE" title="Current Scripture context" body="Sensitive journal content is intentionally not read by this shell." href={notion.spiritual} label="Open Scripture surface"/><ModuleCard eyebrow="ACTIVE PRAYER" title="Protected prayer context" body="Prayer records remain private and outside the shell allowlist." href={notion.prayer} label="Open Prayer Registry"/></section><section className="os-reflective"><ToolFrame title="Prayer session timer" src="/widgets/session?theme=spiritual-minimal&compact=true&mode=prayer"/><ModuleCard eyebrow="REFLECTIVE CONTEXT" title="Prayer before playback" body="The local prayer session remains available beside a calm media environment. P05/P06 reads remain off." href={notion.spiritual} label="Open Spiritual Center"/></section><MediaTheater mode="spiritual" embedded/></>;
  if(mode==="brand")return <><section className="os-mode-grid"><ModuleCard eyebrow="ACTIVE CREATIVE CONTEXT" title="Protected brand work" body={d.emptyState} href={notion.brand} label="Open active assets"/><ModuleCard eyebrow="CONTENT PIPELINE" title="Create, review, release" body="The pipeline remains canonical in Brand Studio; no P07 access was added." href={notion.brand} label="Open pipeline"/></section><MediaTheater mode="brand" embedded/><ModuleCard eyebrow="AUTHORITY / READY" title="Publish from governed truth" body="Review authority and ready items in the existing Brand Studio before release." href={notion.brand} label="Review ready items"/></>;
  if(mode==="growth")return <><section className="os-mode-grid"><ModuleCard eyebrow="CURRENT STUDY" title="Learning focus" body={d.emptyState} href={notion.growth} label="Open current study"/><ModuleCard eyebrow="STUDY TIMER" title="Protect the learning window" body="Reuse the certified local focus timer without a P12 write." href="/widgets/focus?theme=personal&compact=true&mode=learning" label="Start study timer"/></section><MediaTheater mode="growth" embedded/><section className="os-mode-grid"><ModuleCard eyebrow="FRAMEWORKS / PROCESSING" title="Work the idea" body="Framework detail remains in the protected Growth and Intelligence surfaces." href={notion.growth} label="Open frameworks"/><ModuleCard eyebrow="FOCUS ENTRY" title="Study one thing deeply" body="Move directly into the low-distraction Focus mode." href="?mode=focus" label="Enter Focus mode"/></section></>;
  return <><section className="os-reset-summary"><ModuleCard eyebrow="OUTCOMES" title={data.focus?.title??"No NOW outcome"} body={data.focus?.detail??d.emptyState} href={data.focus?.href??notion.reset} label="Open in Notion"/><ModuleCard eyebrow="COMMITMENTS" title={`${data.attention.filter(item=>item.kind==="COMMITMENT").length} requiring attention`} body="Review active commitments before preparing the next week." href={notion.commitment} label="Open in Notion"/><ModuleCard eyebrow="RHYTHMS" title={`${data.rhythms.active} active`} body={`${data.rhythms.healthy} healthy · ${data.rhythms.attention} need attention`} href={notion.reset} label="Open in Notion"/></section><section className="os-split"><div><SectionTitle eyebrow="OPEN DECISIONS" title="Close the decision loop"/><CompactList items={data.decisions} empty="No open decisions require attention." type="Decision" context="Reset"/></div><div><SectionTitle eyebrow="SIGNALS" title="Carry forward what matters"/><CompactList items={data.signals} empty="No notable signals are currently populated." type="Signal" context="Reset"/></div></section><section className="os-mode-grid"><ModuleCard eyebrow="REFLECTION" title="What worked? What needs to change?" body="Use the native weekly review prompts to reflect without creating a new automation." href={notion.reset} label="Open in Notion"/><ModuleCard eyebrow="NEXT WEEK" title="Prepare deliberately" body="Choose the next outcome, commitments, and rhythm adjustments in the certified workspace." href={notion.reset} label="Open in Notion"/></section></>;
}

function BusinessStateCards({data}:{data:BusinessCommandData}){return <><article><p className="os-eyebrow">WORKTELLI</p><h2>{data.worktelli.productState}</h2><p>{data.worktelli.generation} · {data.worktelli.certification}</p><span>{data.worktelli.primaryConstraint}</span><a href={notion.worktelli} target="_blank" rel="noreferrer">Open product control ↗</a></article><article><p className="os-eyebrow">REVENUE</p><h2>{data.revenue.activeCount} active</h2><p>{new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(data.revenue.estimatedValue)} canonical pipeline</p><span>{data.revenue.topOpportunity?.title??"No live opportunity populated"}</span><a href={data.revenue.topOpportunity?.href??notion.revenue} target="_blank" rel="noreferrer">Open revenue command ↗</a></article><article><p className="os-eyebrow">WORKFORCE</p><h2>{data.workforce.totalActive} active</h2><p>{data.workforce.healthy} healthy · {data.workforce.degraded+data.workforce.waiting+data.workforce.attention+data.workforce.offline} attention</p><span>{data.workforce.offline} offline</span><a href={notion.workforce} target="_blank" rel="noreferrer">Open workforce control ↗</a></article></>}
function Pulse({data}:{data:BusinessCommandData}){return <dl className="os-pulse-line">{data.pulse.map(item=><div key={item.label}><dt>{item.label}</dt><dd data-tone={item.tone}>{item.value}</dd></div>)}</dl>}
function BusinessExecutive({data}:{data:BusinessCommandData}){return <><section className="os-requires"><SectionTitle eyebrow="REQUIRES DAVID" title="Executive attention"/><CompactList items={data.requiresDavid} empty="No executive decisions or exceptions require attention."/></section><section className="os-business-grid"><BusinessStateCards data={data}/></section><section className="os-pulse"><SectionTitle eyebrow="EXECUTIVE PULSE" title="Operating state"/><Pulse data={data}/></section><section className="os-split"><div><SectionTitle eyebrow="OPEN DECISIONS" title="Decision queue" action={{label:"Business decisions",href:notion.businessDecision}}/><CompactList items={data.decisions} empty="No open business decisions."/></div><div><SectionTitle eyebrow="INTELLIGENCE" title="Material signals" action={{label:"Signal registry",href:notion.businessSignal}}/><CompactList items={data.signals} empty="No material business signals are currently populated."/></div></section><section className="os-split"><div><SectionTitle eyebrow="OPEN EXCEPTIONS" title="Constraint watch" action={{label:"Exception center",href:notion.exception}}/><CompactList items={data.exceptions} empty="No active exceptions."/></div><div className="os-capture"><SectionTitle eyebrow="QUICK ACTIONS" title="Capture canonical work"/><div><ActionButton actionId="A-B01"/><ActionButton actionId="A-B04"/><ActionButton actionId="A-B02" preset={{category:"EXECUTIVE"}}/><a href={notion.initiative} target="_blank" rel="noreferrer">+ Initiative</a><ActionButton actionId="A-B03"/></div><p>Approved actions use bounded writes. Initiatives remain in the native workflow.</p></div></section></>}

function BusinessModeContent({mode,data}:{mode:BusinessMode;data:BusinessCommandData}){
  const d=businessModeRegistry[mode];
  if(mode==="executive")return <BusinessExecutive data={data}/>;
  if(mode==="revenue")return <><section className="os-revenue-hero"><div><p className="os-eyebrow">OPPORTUNITY RADAR</p><h2>{data.revenue.topOpportunity?.title??"No live opportunity populated"}</h2><p>{data.revenue.topOpportunity?.detail??d.emptyState}</p>{data.revenue.topOpportunity?<DetailDrawerTrigger label="Inspect opportunity" record={{title:data.revenue.topOpportunity.title,type:"Opportunity",status:data.revenue.topOpportunity.detail.split(" · ")[0],summary:data.revenue.topOpportunity.detail,href:data.revenue.topOpportunity.href,context:"Revenue",properties:[{label:"Estimated value",value:data.revenue.estimatedValue?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(data.revenue.estimatedValue):null}]}}/>:null}</div><dl><div><dt>Active pipeline</dt><dd>{data.revenue.activeCount}</dd></div><div><dt>Estimated value</dt><dd>{new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(data.revenue.estimatedValue)}</dd></div></dl></section><section className="os-mode-grid"><ModuleCard eyebrow="CLOSING STATE" title={data.revenue.topOpportunity?"Next opportunity in view":"Pipeline is truthful and empty"} body="Closing state is derived only from authorized B03 canonical records." href={notion.revenue} label="Open in Notion"/><ModuleCard eyebrow="FOLLOW-UP ATTENTION" title="Commercial follow-up" body="Account-level detail remains bounded because B01 is not a shell read source." href={notion.revenue} label="Open in Notion"/></section><section className="os-split"><div><SectionTitle eyebrow="COMMERCIAL SIGNALS" title="Market intelligence"/><CompactList items={data.signals} empty="No commercial signals are currently populated." type="Business Signal" context="Revenue"/></div><div><SectionTitle eyebrow="COMMERCIAL DECISIONS" title="Decision queue"/><CompactList items={data.decisions} empty="No commercial decisions are open." type="Business Decision" context="Revenue"/></div></section><ModuleCard eyebrow="STRATEGIC ACCOUNTS" title="Bounded account context" body="Strategic account records remain in native Revenue Command; no B01 access was added." href={notion.revenue} label="Open in Notion"/></>;
  if(mode==="worktelli")return <><section className="os-product-state"><ModuleCard eyebrow="WORKTELLI STATE" title={data.worktelli.productState} body={`${data.worktelli.generation} · ${data.worktelli.certification}`} href={notion.worktelli} label="Open product control"/><ModuleCard eyebrow="CURRENT CONSTRAINT" title={data.worktelli.primaryConstraint} body="Constraint state is derived from authorized business sources." href={notion.exception} label="Review exceptions"/><ModuleCard eyebrow="QUALIFICATION" title={data.worktelli.latestQualification} body="No runtime or GitHub access was added." href={notion.worktelli} label="Review qualification"/><ModuleCard eyebrow="CURRENT PACKET" title={data.worktelli.currentPacket} body="Engineering packet context remains read-only." href={notion.engineering} label="Open packet"/></section><section className="os-split"><div><SectionTitle eyebrow="PRODUCT DECISIONS" title="Decision queue"/><CompactList items={data.decisions} empty="No product decisions are currently open."/></div><div><SectionTitle eyebrow="PRODUCT EXCEPTIONS" title="Constraint watch"/><CompactList items={data.exceptions} empty="No product exceptions are active."/></div></section><section className="os-split"><div><SectionTitle eyebrow="CAPABILITIES" title="Certified product state"/><p className="os-empty">Capability detail remains canonical in Worktelli Control.</p></div><div><SectionTitle eyebrow="SIGNALS" title="Product intelligence"/><CompactList items={data.signals} empty="No product signals are currently populated."/></div></section></>;
  if(mode==="engineering")return <><section className="os-engineering-hero"><div><p className="os-eyebrow">CURRENT ENGINEERING PACKET</p><h2>{data.worktelli.currentPacket}</h2><p>Release and qualification truth remain bounded to certified Business sources.</p><a href={notion.engineering} target="_blank" rel="noreferrer">Open Engineering Control ↗</a></div><div><p className="os-eyebrow">QUALIFICATION / RELEASE</p><strong>{data.worktelli.latestQualification}</strong><span>{data.worktelli.certification}</span></div></section><section className="os-split"><div><SectionTitle eyebrow="OPEN ENGINEERING EXCEPTIONS" title="Technical constraints"/><CompactList items={data.exceptions} empty="No open engineering exceptions are available."/></div><div><SectionTitle eyebrow="ENGINEERING DECISIONS" title="Decision queue"/><CompactList items={data.decisions} empty="No open engineering decisions are available."/></div></section><ModuleCard eyebrow="CURRENT CONSTRAINT" title={data.worktelli.primaryConstraint} body="No GitHub, production, or external runtime access was introduced." href={notion.engineering} label="Open governed source"/></>;
  if(mode==="clients")return <><section className="os-client-hero"><ModuleCard eyebrow="ACTIVE CLIENTS" title="Protected client portfolio" body={d.emptyState} href={notion.clients} label="Open Client Command"/><ModuleCard eyebrow="CLIENT-RELATED OPPORTUNITIES" title={`${data.revenue.activeCount} active business opportunities`} body="The shell does not infer which B03 records are client-related without authorized B01/B02 context." href={notion.revenue} label="Review opportunities"/></section><section className="os-split"><div><SectionTitle eyebrow="RISK / EXCEPTIONS" title="Available business exceptions"/><CompactList items={data.exceptions} empty="No active exceptions are currently available."/></div><div><SectionTitle eyebrow="SIGNALS" title="Available business signals"/><CompactList items={data.signals} empty="No material signals are currently populated."/></div></section></>;
  return <><section className="os-workforce-hero"><div><p className="os-eyebrow">DIGITAL WORKFORCE STATUS</p><h2>{data.workforce.totalActive} active</h2><p>{data.workforce.healthy} healthy · {data.workforce.attention+data.workforce.waiting+data.workforce.degraded+data.workforce.offline} requiring attention</p></div><dl><div><dt>Healthy</dt><dd>{data.workforce.healthy}</dd></div><div><dt>Waiting</dt><dd>{data.workforce.waiting}</dd></div><div><dt>Degraded</dt><dd>{data.workforce.degraded}</dd></div><div><dt>Offline</dt><dd>{data.workforce.offline}</dd></div></dl></section><section className="os-mode-grid"><ModuleCard eyebrow="WORKERS REQUIRING ATTENTION" title={`${data.workforce.attention+data.workforce.waiting+data.workforce.degraded+data.workforce.offline}`} body={data.workforce.totalActive?"Review the canonical workforce state.":d.emptyState} href={notion.workforce} label="Open workforce"/><ModuleCard eyebrow="FUNCTION DISTRIBUTION" title="Canonical B08 view" body="Function-level detail remains in Workforce Control; no values are inferred." href={notion.workforce} label="Review functions"/></section><section className="os-split"><div><SectionTitle eyebrow="EXCEPTIONS" title="Operational constraints"/><CompactList items={data.exceptions} empty="No workforce exceptions are active."/></div><div><SectionTitle eyebrow="METRICS / EXECUTIVE WORKERS" title="Operating pulse"/><Pulse data={data}/></div></section></>;
}

export function PersonalCommandShell(){const search=useSearchParams();const mode=parsePersonalMode(search.get("mode"));const d=personalModeRegistry[mode];const {result,retry}=useCommandData<PersonalCommandData>("/api/os/personal/command","personal");return <main className="os-shell os-personal" data-mode={mode}><header className="os-header"><div><p className="os-eyebrow">CRAIG OS · PERSONAL</p><h1>{d.heading}</h1><p>{d.subheading}</p></div><LiveContext personal/></header><OsSwitcher scope="personal"/><ModeRail modes={personalModes} current={mode} registry={personalModeRegistry}/><ModeIntro definition={d}/>{result.state==="loading"?<ShellLoading/>:result.state==="error"?<ShellError detail={result.detail} retry={retry} href={notion.personalCommand}/>:<div className="os-mode-content" key={mode}><PersonalModeContent mode={mode} data={result.data}/><ActionTray definition={d}/><Freshness at={result.generatedAt}/></div>}<footer className="os-footer"><span>Craig OS v0.11.1</span><span>Direct mobile app · Governed Action Layer · Media Theater</span></footer></main>}
export function BusinessCommandShell(){const search=useSearchParams();const mode=parseBusinessMode(search.get("mode"));const d=businessModeRegistry[mode];const {result,retry}=useCommandData<BusinessCommandData>("/api/os/business/command","business");return <main className="os-shell os-business" data-mode={mode}><header className="os-header"><div><p className="os-eyebrow">PRODIGYIQ TECHNOLOGIES</p><h1>{d.heading}</h1><p>{d.subheading}</p></div><LiveContext/></header><OsSwitcher scope="business"/><ModeRail modes={businessModes} current={mode} registry={businessModeRegistry}/><ModeIntro definition={d}/>{result.state==="loading"?<ShellLoading/>:result.state==="error"?<ShellError detail={result.detail} retry={retry} href={notion.businessCommand}/>:<div className="os-mode-content" key={mode}><BusinessModeContent mode={mode} data={result.data}/><ActionTray definition={d}/><Freshness at={result.generatedAt}/></div>}<footer className="os-footer"><span>Craig OS v0.11.1</span><span>Direct mobile app · Governed Action Layer · Media Theater</span></footer></main>}
